"""Stage 6 — report. corpus_v0.md: sizes, dedup rates, bot-stubs, audit, caveats.

docs/phase-0.md A2.6: docs + size by source/origin/genre in bytes, chars,
whitespace words, and tokens under a NAMED reference tokenizer (o200k); dedup
removal rates + duplicate-map summary; bot-stub share of Wikipedia; top crawl
domains (if URLs exist); audit first-pass; caveats. The ~90–100M figure is an
estimate, NOT a completion criterion — this reports what is actually there.

Run:  python -m corpus.report [--sample]
"""

from __future__ import annotations

import argparse
import json
import os
from collections import defaultdict

from . import common, config


def _load_json(path, default=None):
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    return default


def _fmt(n):
    return f"{n:,}"


def _size_tables(docs, tok):
    """Sizes by source / origin / genre in bytes, chars, ws-words, o200k tokens."""
    dims = {"source": defaultdict(lambda: [0, 0, 0, 0, 0]),
            "origin": defaultdict(lambda: [0, 0, 0, 0, 0]),
            "genre": defaultdict(lambda: [0, 0, 0, 0, 0])}
    totals = [0, 0, 0, 0, 0]  # docs, bytes, chars, ws_words, tokens
    for d in docs:
        t = d["text"]
        row = [1, common.n_bytes(t), common.n_chars(t), common.n_ws_words(t), tok.count(t)]
        for dim, key in (("source", d["acquisition"]["source"]),
                         ("origin", d["origin"]), ("genre", d["genre"])):
            acc = dims[dim][key]
            for i in range(5):
                acc[i] += row[i]
        for i in range(5):
            totals[i] += row[i]
    return dims, totals


def _probe_contamination(docs):
    """Do held-out probe proverbs leak into the TRAINING corpus via crawl/wiki?

    The probe holdout removes only the OWNED proverb copy; a famous proverb can
    still occur inside a MADLAD/Wikipedia doc. Reports per-probe hit counts so a
    reviewer knows which probe items are contaminated (splits.yaml's n-gram
    contamination check is the training-time backstop).
    """
    if not os.path.exists(config.PROVERBS_PROBE_LOCAL):
        return None
    probes = list(common.read_jsonl(config.PROVERBS_PROBE_LOCAL))
    keys = [(p["proverb_num"], common.nfc(p["text"]).casefold(), p["text"]) for p in probes]
    train_texts = [common.nfc(d["text"]).casefold() for d in docs
                   if d.get("split") == "train"]
    hits = []
    for num, needle, original in keys:
        c = sum(1 for t in train_texts if needle in t)
        hits.append({"num": num, "text": original, "train_hits": c})
    return hits


def _table(title, mapping, totals):
    out = [f"### By {title}", "",
           f"| {title} | docs | bytes | chars | whitespace words | o200k tokens |",
           "|---|--:|--:|--:|--:|--:|"]
    for key in sorted(mapping, key=lambda k: -mapping[k][4]):
        r = mapping[key]
        out.append(f"| {key} | {_fmt(r[0])} | {_fmt(r[1])} | {_fmt(r[2])} | {_fmt(r[3])} | {_fmt(r[4])} |")
    out.append(f"| **total** | {_fmt(totals[0])} | {_fmt(totals[1])} | {_fmt(totals[2])} "
               f"| {_fmt(totals[3])} | {_fmt(totals[4])} |")
    out.append("")
    return out


def build_report(sample: bool):
    tag = common.run_tag(sample)
    corpus = os.path.join(config.CLEAN, f"corpus_v0-{tag}.jsonl")
    docs = list(common.read_jsonl(corpus))
    tok = common.RefTokenizer()

    dims, totals = _size_tables(docs, tok)

    fstats = {s: _load_json(common.stage_path(tag, "filter", s).replace(f"{s}.jsonl", f"{s}.stats.json"))
              for s in config.PIPELINE_SOURCES}
    dstats = _load_json(common.stage_path(tag, "dedup", "dedup").replace(".jsonl", ".stats.json"), {})
    audit = _load_json(os.path.join(config.REPORTS, f"audit_summary-{tag}.json"), {})

    # bot-stub share of Wikipedia in the FINAL corpus
    wiki = [d for d in docs if d["acquisition"]["source"] == config.HTWIKI_SOURCE_KEY]
    wiki_stub = sum(1 for d in wiki if d.get("wiki_bot_stub"))
    wiki_share = (wiki_stub / len(wiki)) if wiki else 0.0

    L = []
    A = L.append
    A("# Corpus v0 — Haitian Creole (Workstream A)")
    A("")
    A(f"*Build snapshot {config.SNAPSHOT_DATE} · run `{tag}`. Generated by `ml/corpus/` "
      "— see [../../docs/phase-0.md](../../docs/phase-0.md) (Workstreams 0 + A) and "
      "[../../docs/plan.md](../../docs/plan.md) §5.2. Rights & splits fixed first in "
      "[`../corpus/rights.yaml`](../corpus/rights.yaml) / "
      "[`../corpus/splits.yaml`](../corpus/splits.yaml).*")
    A("")
    if sample:
        A("> ⚠️ **This is the 1% smoke-test build**, not the full corpus. Numbers are "
          "illustrative; see the `full` build for real sizes.")
        A("")

    # --- headline ---
    A("## What is actually there")
    A("")
    A(f"Corpus v0 (rights-clear sources only, deduplicated) is **{_fmt(totals[0])} documents** — "
      f"**{_fmt(totals[1])} bytes**, **{_fmt(totals[2])} chars**, **{_fmt(totals[3])} whitespace "
      f"words**, **{_fmt(totals[4])} tokens** under the reference tokenizer "
      f"`{tok.name}` (o200k_base, the same unit Workstream C reports).")
    A("")
    A("The phase-0 plan's ~90–100M-token figure is an **estimate, not a target**: this is "
      "what the clean build actually contains. (MADLAD's own count is ~84.3M whitespace-ish "
      "\"tokens\" over 110,443 raw docs — a *different* unit from o200k tokens; the two are "
      "not comparable.)")
    A("")

    # --- size tables ---
    A("## Sizes")
    A("")
    A("Four units per docs/phase-0.md A6. \"Tokens\" throughout = `o200k_base` "
      "(named reference tokenizer), **not** our future Kreyòl BPE (Workstream B).")
    A("")
    L += _table("source", dims["source"], totals)
    L += _table("origin", dims["origin"], totals)
    L += _table("genre", dims["genre"], totals)
    A("> `origin=web_crawl` and `genre=web` are additions to docs/plan.md §5.2's written "
      "enums, used for MADLAD crawl text so we don't assert authorship (`authored_kreyol`) "
      "or a translation origin we can't verify. See `corpus/schema.py`.")
    A("")

    # --- dedup ---
    A("## Deduplication")
    A("")
    din = dstats.get("input_docs", 0)
    de = dstats.get("document_exact_removed", 0)
    dn = dstats.get("document_near_removed", 0)
    pe = dstats.get("paragraph_exact_removed", 0)
    dd = dstats.get("paragraph_dropped_docs", 0)
    fin = dstats.get("final_docs", 0)
    rate = ((din - fin) / din) if din else 0.0
    A(f"Exact (content hash) → near-dup (MinHash/LSH, {config.SHINGLE_N}-gram word shingles, "
      f"Jaccard ≥{config.MINHASH_THRESHOLD}, {config.MINHASH_NUM_PERM} perms) at document level, "
      "then paragraph-level exact-dup across sources. Survivor priority "
      "**owned > wikipedia > crawl**, tie-broken by longer text then doc id.")
    A("")
    A("| stage | removed |")
    A("|---|--:|")
    A(f"| input documents | {_fmt(din)} |")
    A(f"| document exact-dup removed | {_fmt(de)} |")
    A(f"| document near-dup removed | {_fmt(dn)} |")
    A(f"| whole docs dropped (all paragraphs duplicated) | {_fmt(dd)} |")
    A(f"| **final documents** | **{_fmt(fin)}** |")
    A(f"| document removal rate | {rate:.1%} |")
    A(f"| paragraph segments removed (boilerplate, across docs) | {_fmt(pe)} |")
    A(f"| docs edited by paragraph dedup | {_fmt(dstats.get('docs_touched_by_paragraph_dedup', 0))} |")
    A(f"| duplicate-map clusters recorded | {_fmt(dstats.get('clusters', 0))} |")
    A("")
    A("Survivors by source priority class: " +
      ", ".join(f"`{k}`={_fmt(v)}" for k, v in dstats.get("survivors_by_priority_class", {}).items()) + ".")
    A("")
    A("The **duplicate map** (`data/interim/" + tag + "/dedup/duplicate_map.jsonl`, git-ignored) "
      "records every cluster: id, level, survivor, why the survivor won, and all members — "
      "so nothing is silently discarded. Paragraph-level **near**-dup is intentionally not run "
      "at full scale (a MinHash per paragraph is ~1–2M objects); it is covered indirectly by "
      "document near-dup + paragraph exact-dup.")
    A("")

    # --- filter ---
    A("## Filtering (source-specific)")
    A("")
    A("Thresholds differ by source (a single floor would delete proverbs and conversational "
      "text while under-filtering crawl). Wikipedia bot-stubs are **flagged, not dropped**.")
    A("")
    A("| source | in | kept | dropped | drop reasons |")
    A("|---|--:|--:|--:|---|")
    for s in config.PIPELINE_SOURCES:
        st = fstats.get(s) or {}
        drops = st.get("dropped", {})
        reasons = ", ".join(f"{k}={v}" for k, v in drops.items()) or "—"
        A(f"| {st.get('source', s)} | {_fmt(st.get('in', 0))} | {_fmt(st.get('kept', 0))} "
          f"| {_fmt(sum(drops.values()))} | {reasons} |")
    A("")

    # --- bot stubs ---
    A("## Wikipedia bot-stubs")
    A("")
    A(f"Haitian Wikipedia is heavily bot-generated. Flagged (short + template-driven, or a "
      f"geo/species-stub opening) in the FINAL corpus: **{_fmt(wiki_stub)} / {_fmt(len(wiki))} "
      f"= {wiki_share:.1%}** of surviving Wikipedia docs. They are kept (real Kreyòl, low "
      "information density) but tagged `wiki_bot_stub=true` so downstream stages can down-weight "
      "or exclude them. This is a heuristic flag, not ground truth.")
    A("")

    # --- proverbs ---
    prov = [d for d in docs if d["acquisition"]["source"] == config.PROVERBS_SOURCE_KEY]
    A("## Owned proverbs (teachable) + probe holdout")
    A("")
    A(f"CreolePro's 50 proverbs are split deterministically (seed "
      f"{config.PROVERBS_SPLIT_SEED}): **{_fmt(len(prov))} teachable** proverbs are in this "
      f"corpus (`split=train`, `genre=proverb`, `origin=authored_kreyol`); "
      f"**{config.PROVERBS_PROBE_N} probe** proverbs are held out in "
      "`data/eval/proverbs_probe.jsonl` and never enter training or the tokenizer — they are "
      "Station 2's \"who knows the real proverb?\" set. Only the Kreyòl text enters the corpus "
      "(English gloss + category are metadata). Tiny by volume, but the highest-quality, "
      "authored Kreyòl in the build.")
    A("")
    contam = _probe_contamination(docs)
    if contam is not None:
        leaked = [c for c in contam if c["train_hits"] > 0]
        A(f"**Probe contamination check.** The holdout removes only the *owned* copy of each "
          f"probe proverb; a famous proverb can still appear inside a MADLAD/Wikipedia doc. "
          f"Exact-substring scan of the training corpus: **{len(leaked)} / {len(contam)} probe "
          "proverbs also occur in training text.** This is expected for well-known proverbs and "
          "is why splits.yaml keeps an n-gram contamination check as the training-time backstop; "
          "for Station 2, prefer probe proverbs with 0 training hits (or accept that the model "
          "may have seen the phrasing via crawl).")
        A("")
        A("| probe # | train hits | proverb |")
        A("|--:|--:|---|")
        for c in sorted(contam, key=lambda x: -x["train_hits"]):
            A(f"| {c['num']} | {c['train_hits']} | {c['text']} |")
        A("")

    # --- MADLAD domains ---
    A("## MADLAD source domains")
    A("")
    A("**Not available.** The released MADLAD-400 ht `clean` JSONL carries only a `text` field "
      "— no per-document URL or domain — so a top-domains breakdown of the crawl slice is not "
      "possible from the data. (The crawl origin is visible in the text of many docs — supplier "
      "listings, product pages — but that is not a reliable domain signal.)")
    A("")

    # --- audit ---
    A("## Quality audit — machine first pass")
    A("")
    if audit:
        o = audit["overall_rates"]
        A(f"Deterministic stratified sample of **{audit['sampled']} docs** (seed "
          f"{audit['seed']}) across sources × length bands. **Rates below are "
          "MACHINE-ESTIMATED (fasttext lid.176 + heuristics) and pending human review.**")
        A("")
        A("| scope | n | wrong_lang | wrong_lang≥300 | low_conf_ht | boilerplate | unreadable |")
        A("|---|--:|--:|--:|--:|--:|--:|")

        def ge(r):
            v = r.get("wrong_language_ge300")
            return "—" if v is None else f"{v:.1%}"
        A(f"| **overall** | {audit['sampled']} | {o['wrong_language']:.1%} | {ge(o)} "
          f"| {o['low_confidence_ht']:.1%} | {o['boilerplate']:.1%} | {o['unreadable']:.1%} |")
        for s, r in audit["per_source_rates"].items():
            n = audit["per_source_n"][s]
            A(f"| {s} | {n} | {r['wrong_language']:.1%} | {ge(r)} | {r['low_confidence_ht']:.1%} "
              f"| {r['boilerplate']:.1%} | {r['unreadable']:.1%} |")
        A("")
        A("**Reading these honestly:** `boilerplate`/`unreadable` are ~0 — a good sign the "
          "filter did its job. The `wrong_language` numbers are an **upper bound that mostly "
          "measures lid.176's weakness on Kreyòl**, not contamination: eyeballing the flagged "
          "docs, they are overwhelmingly genuine Kreyòl encyclopedic stubs dense with "
          "French/Spanish proper nouns (foreign actor names, film titles) that tip langid to "
          "`fr`/`es`/`tl`. Restricting to docs ≥300 chars does not fix it — langid simply "
          "under-detects Haitian Creole. `low_conf_ht` (langid picked `ht` but with low "
          "confidence) is high for the same reason. **Human review is the actual audit; this "
          "is the machine first pass that tells a reviewer where to look.** The full sample "
          "with text is in the git-ignored `ml/reports/audit_sample.jsonl`; a committable "
          "review sheet is [`audit_sample_review.md`](audit_sample_review.md).")
    else:
        A("_No audit summary found._")
    A("")

    # --- caveats ---
    A("## Caveats & what needs human review")
    A("")
    A("- **MADLAD license unresolved (CC-BY-4.0 vs ODC-BY).** Redistribution stays blocked "
      "and MADLAD text is not excerpted in committed files (audit snippets redacted) until "
      "resolved — see `rights.yaml`. Analysis/tokenizer/model-training are permitted under "
      "either candidate license.")
    A("- **MADLAD is crawl, not authored.** Visible commercial boilerplate (supplier/product "
      "pages) and occasional mojibake survive filtering; this is translation-shaped, "
      "machine-aligned web text, not authored Kreyòl. `origin=web_crawl`.")
    A("- **Wikipedia is bot-stub-heavy** (see above) — flagged, not authored-labeled.")
    A("- **langid is unreliable for Kreyòl** — the wrong-language rate is a tooling artifact "
      "as much as a corpus signal. Needs a fluent reviewer.")
    A("- **Owned proverbs** (CreolePro's 50) are the only authored, non-crawl, non-encyclopedic "
      "source: 35 teachable proverbs entered training; 15 probe proverbs are held out "
      "(`data/eval/proverbs_probe.jsonl`, never trained) for Station 2. They are a tiny slice "
      "by volume but the highest-quality Kreyòl in the corpus.")
    A("- Quarantined sources (MIT-Haiti, dictionary) and eval-only FLORES+ are **not** in this "
      "corpus, by design.")
    A("")
    A("## Reproduce")
    A("")
    A("```bash")
    A("cd ml && uv sync")
    A("uv run python -m corpus.run --sample   # 1% smoke test, end to end")
    A("uv run python -m corpus.run            # full build + audit + this report")
    A("```")
    A("")
    A(f"Sources pinned: MADLAD `{config.MADLAD_REPO}` @ `{config.MADLAD_REVISION[:12]}` "
      f"(ht clean); htwiki dump `{config.HTWIKI_DUMP_DATE}`. Seeds: sample "
      f"{config.SAMPLE_SEED}, audit {config.AUDIT_SEED}.")

    out = os.path.join(config.REPORTS, "corpus_v0.md" if not sample else "corpus_v0-sample.md")
    os.makedirs(config.REPORTS, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    common.log(f"  report -> {out}")
    return out, totals


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sample", action="store_true")
    args = ap.parse_args()
    common.log(f"[report] sample={args.sample}")
    build_report(args.sample)


if __name__ == "__main__":
    main()
