"""Render ml/reports/sweep4_ingest.md + ml/reports/heritage_cric_crac_fable.md.

Repo convention: this string-builder IS the template; re-run to regenerate. Reads
the v0.2.1 build stats + the sweep4 ingest stats + the held-out heritage fable JSON
(all git-ignored under data/).

Run:  uv run python -m corpus.report_v0_2_1
"""

from __future__ import annotations

import json
import os
import re

from . import common, config
from . import config_v0_2 as C2
from .sweep4 import _score  # historical Kreyòl-vs-French line scorer

# The facing La Fontaine French lines share vocabulary with Kreyòl (tout/loup/pas),
# so the marker score alone can't separate them — but they use French spellings the
# 1901 Kreyòl never does (cabri≠cabritt, chèvre, n'est, couarde). Veto those for the
# exhibit only (the corpus keeps page-level separation).
_FR_VETO = {"cabri", "chèvre", "chevreau", "couarde", "n'est", "c'est",
            "était", "toutes", "bêtes", "chbvre", "assieds"}


def _try(path):
    if os.path.exists(path):
        return json.load(open(path, encoding="utf-8"))
    return None


def _m(x):
    return f"{x/1e6:.2f}M"


# --------------------------------------------------------------------------- #
# sweep4_ingest.md
# --------------------------------------------------------------------------- #
def build_report():
    bs = _try(C2.V0_2_1_STATS.format(tag="full"))
    sw = _try(os.path.join(config.DATA, "interim", "sweep4_stats.json")) or {}
    L = []
    A = L.append
    A("# Sweep-4 ingest — corpus v0.2.1 addendum (Workstream J-ADDENDUM)")
    A("")
    A("*Generated by `ml/corpus/report_v0_2_1.py` from the build sidecars "
      "(git-ignored under `data/`). Token unit **kreyol-bpe**. This is an "
      "INCREMENTAL build on top of the frozen corpus v0.2 (see "
      "[corpus_v0_2.md](corpus_v0_2.md)): the four verified TRAIN-OK sweep-4 sources "
      "(docs/data.md §1 sweep-4 rows) are deduped STRICTLY — exact + MinHash — "
      "against the FULL v0.2 corpus and appended. They add register COVERAGE "
      "(translated newswire, historical literary), not scale.*")
    A("")

    if not bs:
        A("> **Build not yet run.** `corpus.build_v0_2_1` has not produced its "
          "build_stats. Run the pipeline (see Reproduce).")
    else:
        # headline
        A("## Headline")
        A("")
        A(f"- **{bs['total_tokens_kb']/1e6:.1f}M** unique kreyol-bpe tokens "
          f"({bs['total_docs']:,} docs) — corpus v0.2 "
          f"{bs['base_v0_2_tokens_kb']/1e6:.1f}M + **{bs['new_survivor_tokens_kb']/1e3:.0f}k "
          f"net-new** from sweep-4 ({bs['new_survivor_docs']:,} docs).")
        A(f"- Registers added: **news_translated, health_translated, "
          f"historical_literary** (all held at mix weight 1× — register coverage, "
          f"not authored-voice amplification; pre-reform orthography stays "
          f"identifiable + down-weightable).")
        A(f"- **3 of 4 sources ingested**; Lessons in Haitian Creole (1921) "
          f"**abandoned on OCR-quality grounds** (see below). One Cric? Crac! fable "
          f"held out entirely as a heritage exhibit.")
        A("")

        # per-source measured table
        A("## Per-source: measured tokens, dedup, probe-check")
        A("")
        A("| source | ingested docs | probe-leak | langid | exact-dup v0.2 | near-dup v0.2 | kept | net-new tok | verdict |")
        A("|---|--:|--:|--:|--:|--:|--:|--:|---|")
        srcstats = bs.get("sources", {})
        for src in ["cmu_haitian", "cric_crac_1901", "anthologie_1925"]:
            s = srcstats.get(src)
            if not s:
                continue
            v = (sw.get(src, {}) or {}).get("verdict", "")
            tok = (sw.get(src, {}) or {}).get("tokens_kb", 0)
            A(f"| {src} | {s['in']:,} | {s['probe_leak']} | {s['langid']} | "
              f"{s['exact_dup_v02']} | {s['near_dup_v02']} | **{s['kept']}** | "
              f"~{tok:,} | {v} |")
        les = sw.get("lessons_haitian_1921", {})
        A(f"| lessons_haitian_1921 | 0 | — | — | — | — | **0** | 0 | "
          f"**{les.get('verdict','abandoned')}** |")
        A(f"| *cross-new dedup removed* | | | | | | −{bs.get('cross_new_dedup_removed',0)} | | |")
        A("")
        A("**Dedup discipline (spec):** CMU newswire overlaps WMT11-era releases and "
          "possibly the crawl, so every sweep-4 doc is checked EXACT (content hash) "
          "**and** MinHash (Jaccard 0.8) against the full v0.2 corpus (v0.1 base + all "
          "J survivors). The check is inverted for memory — a tiny LSH over the few "
          "hundred sweep-4 candidates, with the 315k-doc v0.2 shard streamed through "
          "it once. Note: CMU sentences are chunked ~40/doc, so cross-corpus overlap "
          "is caught at chunk granularity; sentence-level exact overlap below the "
          "document Jaccard threshold is not separately chased (same documented limit "
          "as `corpus/dedup.py`).")
        A("")
        A("**Probe-proverb guard (standing rule):** load-bearing for Cric? Crac! "
          "(these are fables — famous proverbs recur). Every page/passage is screened "
          "against the 15 held-out probe proverbs before it can enter training; "
          f"pages excluded: Cric {sw.get('cric_crac_1901',{}).get('probe_pages_excluded',0)}, "
          f"Anthologie {sw.get('anthologie_1925',{}).get('probe_pages_excluded',0)}.")
        A("")

        # nutrition label v2.1
        A("## Nutrition label v2.1 (composition by register)")
        A("")
        comp = bs["composition_by_register"]
        A("| register | docs | kreyol-bpe tokens | share | mix weight |")
        A("|---|--:|--:|--:|--:|")
        for reg, g in sorted(comp.items(), key=lambda kv: -kv[1]["tokens"]):
            share = g["tokens"] / bs["total_tokens_kb"] if bs["total_tokens_kb"] else 0
            w = C2.MIX_WEIGHTS.get(reg, 1.0)
            star = " ⬅ new" if reg in ("news_translated", "health_translated",
                                       "historical_literary") else ""
            A(f"| {reg}{star} | {g['docs']:,} | {g['tokens']:,} | {share:.2%} | {w}× |")
        A(f"| **total** | **{bs['total_docs']:,}** | **{bs['total_tokens_kb']:,}** | 100% | |")
        A("")

    # OCR / extraction verdicts
    A("## OCR / extraction quality verdicts")
    A("")
    cmu = sw.get("cmu_haitian", {})
    cric = sw.get("cric_crac_1901", {})
    anth = sw.get("anthologie_1925", {})
    les = sw.get("lessons_haitian_1921", {})
    A(f"- **CMU Haitian Corpus — usable (no OCR).** Direct text download under the "
      f"CMU permissive license. Newswire {cmu.get('newswire_sentences','?')} + "
      f"medical {cmu.get('medical_sentences','?')} translated sentences → "
      f"{cmu.get('docs','?')} chunked docs. The `glossary-all-fix.{{ht,en}}` "
      f"**dictionary → {cmu.get('lexicon_pairs','?')} EN↔HT lexicon pairs** "
      f"(`data/interim/v0_2_1_ingest/cmu_lexicon.json`, git-ignored) — a lexicon "
      f"resource, deliberately **NOT** mixed into the LM training text (may feed "
      f"SFT/eval later).")
    A(f"- **Cric? Crac! (1901) — usable, rough OCR.** Sourced from dLOC's own "
      f"page-level OCR (`UF00076576`, patron API `pagetext`, 241 pages) — the "
      f"Creighton 1901 item has no scan bitstreams. The book prints facing French "
      f"(La Fontaine) + Kreyòl; page-level language separation keeps the "
      f"HT-dominant pages → {cric.get('docs','?')} fable-run docs. 1901 pre-reform "
      f"orthography preserved EXACTLY (artifacts: `9a`=ça/sa, `6`=é, `td`=te, "
      f"`gnou`=yon). One complete fable held out for the exhibit.")
    A(f"- **Anthologie d'un siècle de poésie haïtienne (1925) — usable, clean.** "
      f"Manioc CC0 PDF has a clean embedded TEXT LAYER (PyMuPDF; no OCR). "
      f"Predominantly French; {anth.get('kreyol_dense_pages','?')} Kreyòl-dense "
      f"pages of {anth.get('pdf_pages','?')} → {anth.get('docs','?')} docs. langid "
      f"fails on the historical orthography, so Kreyòl passages were isolated by a "
      f"marker pass then reviewed.")
    A(f"- **Lessons in Haitian Creole (1921) — ABANDONED.** {les.get('reason','')} "
      f"(measured: {les.get('kreyol_lines','?')} Kreyòl-ish lines / "
      f"{les.get('clean_kreyol_chars','?')} clean chars in the IA `_djvu.txt`). "
      f"TRAIN-OK by rights (PD); recorded, not ingested.")
    A("")

    # heritage fable
    A("## Heritage exhibit — oldest text connected to the model")
    A("")
    hf = _try(os.path.join(C2.V0_2_1_INGEST, "_cric_heritage_fable.json"))
    if hf:
        A(f"One complete Cric? Crac! (1901) fable — **\"Le Loup, la Chèvre et le "
          f"Chevreau\"** (the wolf-at-the-door / password fable), dLOC pageorders "
          f"{hf['span'][0]}–{hf['span'][1]} (~{hf['tokens_kb']} kreyol-bpe tokens) — "
          f"is held out of training **entirely** and saved as "
          f"[heritage_cric_crac_fable.md](heritage_cric_crac_fable.md). It is not in "
          f"the v0.2.1 shard (leak-check in build_stats: "
          f"{bs.get('heritage_fable_leak_check','?') if bs else '?'}). \"The oldest "
          f"text connected to the model\" is only an exhibit fact if the model never "
          f"trained on it.")
    A("")

    A("## Reproduce")
    A("")
    A("```bash")
    A("cd ml && uv sync")
    A("uv run python -m corpus.sweep4 all          # download + extract (CMU/Cric/Anthologie; Lessons measured)")
    A("uv run python -m corpus.build_v0_2_1         # dedup vs full v0.2 (streamed) + append -> v0.2.1")
    A("uv run python -m corpus.report_v0_2_1        # this report + the heritage asset")
    A("```")
    A("")
    A("Nothing under `ml/data/` is committed. No new committable data artifact here "
      "(the CMU lexicon is git-ignored under `data/`); the only committed outputs are "
      "this report, the heritage fable exhibit, and the registry/doc updates.")

    out = os.path.join(config.REPORTS, "sweep4_ingest.md")
    os.makedirs(config.REPORTS, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    common.log(f"  wrote {out}")
    return out


# --------------------------------------------------------------------------- #
# heritage_cric_crac_fable.md — curated exhibit (raw 1901 OCR, French dropped)
# --------------------------------------------------------------------------- #
def build_heritage():
    hf = _try(os.path.join(C2.V0_2_1_INGEST, "_cric_heritage_fable.json"))
    if not hf:
        common.log("  (no heritage fable json; run corpus.sweep4 cric first)")
        return None
    # strict Kreyòl-only pass for exhibit cleanliness (drop the facing La Fontaine
    # French lines that leak through); Kreyòl orthography itself is preserved EXACTLY.
    # Threshold ≥3 markers: the French translation lines score ≤2, the Kreyòl verse
    # lines carry several distinctive markers.
    kre = []
    for ln in hf["text"].split("\n"):
        s = ln.strip()
        if not s:
            continue
        if set(re.findall(r"[a-zà-ÿ']+", s.lower())) & _FR_VETO:
            continue
        k, f, e = _score(s)
        if k > f and k >= 3:
            kre.append(s)
    body = "\n".join(kre)

    L = []
    A = L.append
    A("# Heritage exhibit — the oldest text connected to the model")
    A("")
    A("> **« Le Loup, la Chèvre et le Chevreau »** — the wolf-at-the-door fable, from")
    A("> **Georges Sylvain, _Cric? Crac!_ (1901)** — the first collection of poems")
    A("> published by a Haitian writer, La Fontaine's fables retold in Kreyòl verse by")
    A("> \"a Haitian montagnard.\" This single fable is held out of the training corpus")
    A("> **entirely** so the exhibit claim stays honest: the model never read it.")
    A("")
    A(f"- **Source:** Digital Library of the Caribbean, "
      f"[UF00076576](https://dloc.com/UF00076576/00001) — the 1901 first edition "
      f"(Ateliers haïtiens; OCLC 06991790; held by the University of Florida). US "
      f"public domain (published before 1929).")
    A(f"- **Provenance:** dLOC's own page-level OCR, pageorders {hf['span'][0]}–"
      f"{hf['span'][1]}. Text reproduced **exactly as digitized** — no orthographic "
      f"normalization.")
    A("- **Register / genre:** `historical_literary` / `historical`, orthography "
      "`pre_reform`.")
    A("")
    A("## The fable (1901 Kreyòl, exactly as OCR'd)")
    A("")
    A("```")
    A(body)
    A("```")
    A("")
    A("## A note on the orthography")
    A("")
    A("This is **pre-reform Haitian Creole**, written in a French-based spelling "
      "decades before the standard IPN/1979 orthography. It is preserved verbatim: it "
      "is a primary historical artifact, and any modernized rendition would be a "
      "separately-reviewed derivative, never a replacement (docs/data.md §4). The "
      "text also carries **1901-print OCR artifacts** — e.g. `9a` for _ça/sa_, `6` for "
      "_é_, `td`/`t6` for _te_, `gnou` for _yon_, `cé` for _se_, stray `<`/`>` for the "
      "French guillemets « ». In modern orthography the opening reads roughly: "
      "_\"Nan tout tan, kabrit ak lou, se tankou lèt ak sitwon…\"_ (\"In all times, "
      "goat and wolf are like milk and lemon…\"). The mother goat, leaving for market, "
      "warns her kid to open the door to no one — until the wolf, hiding behind a "
      "thorn-bush, apes her voice at the door. The kid, unfooled, refuses. It is small, "
      "funny, and unmistakably Haitian — the reason it makes a good first stone in the "
      "model's lineage.")
    A("")
    A("*Held out of training in `corpus/build_v0_2_1.py` (heritage-fable leak-check "
      "asserted at build). Registered in `splits.yaml` → `heritage_exhibits`.*")

    out = C2.HERITAGE_FABLE_MD
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    common.log(f"  wrote {out}")
    return out


if __name__ == "__main__":
    build_heritage()
    build_report()
