"""Render ml/reports/corpus_v0_2.md from the J build sidecars.

Repo convention: this Python string-builder IS the template; re-run to regenerate.
Reads data/clean/corpus_v0_2-full.build_stats.json + data/interim/{family,federal}
_stats.json + data/voa/crawl_state.json + data/interim/j0/*.json.

Run:  uv run python -m corpus.report_v0_2
"""

from __future__ import annotations

import json
import os

from . import common, config, j0_scoping
from . import config_v0_2 as C2


def _try(path):
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    return None


def _m(x):
    return f"{x/1e6:.2f}M"


def _eff_authored_share(comp, weights):
    """Effective authored/register share of the TRAIN mixture under the sampling
    weights: Σ(wᵣ·tokensᵣ, authored) / Σ(wᵣ·tokensᵣ). web_crawl is the only
    non-authored register."""
    num = sum(g["tokens"] * weights.get(r, 1.0)
              for r, g in comp.items() if r != "web_crawl")
    den = sum(g["tokens"] * weights.get(r, 1.0) for r, g in comp.items())
    return num / den if den else 0.0


def build():
    bs = _try(C2.V0_2_STATS.format(tag="full"))
    fam = _try(os.path.join(config.DATA, "interim", "family_stats.json"))
    fed = _try(os.path.join(config.DATA, "interim", "federal_stats.json"))
    voa = _try(C2.VOA_STATE)
    fw0 = _try(os.path.join(j0_scoping.J0_DIR, "fineweb2.json"))

    L = []
    A = L.append
    A("# Corpus v0.2 — composition, dedup, nutrition label v2 (Workstream J)")
    A("")
    A("*Generated by `ml/corpus/report_v0_2.py` from the build sidecars "
      "(git-ignored under `data/`). Token unit **kreyol-bpe**. Design (chosen at "
      "the J0 gate): keep v0.1 frozen, add the NET-NEW J-source survivors "
      "register-tagged, and drive authored/register emphasis via **train-mix "
      "weights**, not corpus composition. Spec: [../../docs/data.md](../../docs/data.md).*")
    A("")

    if not bs:
        A("> **Build not yet run.** `corpus.build_v0_2` has not produced "
          "`corpus_v0_2-full.build_stats.json`. Run the pipeline (see Reproduce).")
    else:
        # headline
        A("## Headline")
        A("")
        A(f"- **{bs['total_tokens_kb']/1e6:.1f}M** unique kreyol-bpe tokens "
          f"({bs['total_docs']:,} docs) — from v0.1's {bs['v01_tokens_kb']/1e6:.1f}M "
          f"(**+{bs['new_survivor_tokens_kb']/1e6:.1f}M net-new**).")
        comp = bs["composition_by_register"]
        authored = sum(g["tokens"] for r, g in comp.items()
                       if r not in ("web_crawl",))
        auth_frac = authored / bs["total_tokens_kb"] if bs["total_tokens_kb"] else 0
        eff = _eff_authored_share(comp, C2.MIX_WEIGHTS)
        A(f"- **{auth_frac:.1%} non-web-crawl by raw token share** — *lower* than "
          f"v0.1's ~10% because fineweb-2's ~105M web-crawl tokens (the volume "
          f"choice) dilute the ratio. This is expected: v0.2 trades raw authored "
          f"share for a data-limited model's token budget + a register tail.")
        A(f"- Applying the register **mix weights** lifts the authored/register "
          f"emphasis to **~{eff:.0%} effective share** of the training mixture — "
          f"real, but **not 30%**. A true 30%-authored mix from this pool would need "
          f"heavy repetition of the ~{authored/1e6:.0f}M authored tokens (overfit "
          f"risk); reaching it cleanly needs permission-route sources (see scoping "
          f"report §5).")
        A(f"- Registers now present: {', '.join(sorted(comp))} — v0.1 had only "
          f"web_crawl + encyclopedic + proverb.")
        A("")

        # composition table
        A("## Composition by register")
        A("")
        A("| register | docs | kreyol-bpe tokens | share | mix weight |")
        A("|---|--:|--:|--:|--:|")
        for reg, g in sorted(comp.items(), key=lambda kv: -kv[1]["tokens"]):
            share = g["tokens"] / bs["total_tokens_kb"] if bs["total_tokens_kb"] else 0
            w = C2.MIX_WEIGHTS.get(reg, 1.0)
            A(f"| {reg} | {g['docs']:,} | {g['tokens']:,} | {share:.1%} | {w}× |")
        A(f"| **total** | **{bs['total_docs']:,}** | **{bs['total_tokens_kb']:,}** | 100% | |")
        A("")
        A("The **mix weight** column is the training-time sampling multiplier "
          "(config_v0_2.MIX_WEIGHTS): web-crawl bulk stays at 1×, authored/register "
          "registers are upweighted. Effective authored/register share of the mixture "
          "= Σ(weightᵣ·tokensᵣ for authored) / Σ(weightᵣ·tokensᵣ) = "
          f"**~{_eff_authored_share(comp, C2.MIX_WEIGHTS):.0%}** at these weights. "
          "Pushing higher means repeating the small authored pool more per epoch "
          "(diminishing returns / overfit) — the honest ceiling of a clean-rights "
          "corpus without a larger authored source.")
        A("")

        # per-source filter + dedup removals
        A("## Per-source filter + dedup removals")
        A("")
        A("| source | ingested | junk | langid | dup-vs-v0.1 | kept |")
        A("|---|--:|--:|--:|--:|--:|")
        for src, s in bs["sources"].items():
            A(f"| {src} | {s['in']:,} | {s['junk']:,} | {s['langid']:,} | "
              f"{s['dup_v01']:,} | **{s['kept']:,}** |")
        A(f"| *cross-new dedup removed* | | | | | −{bs.get('cross_new_dedup_removed',0):,} |")
        A("")
        rc = bs.get("religious_cap", {})
        if rc.get("capped"):
            A(f"**Religious cap** (≤{C2.RELIGIOUS_CAP_FRAC:.0%}): Bib La trimmed "
              f"{rc['rel_tokens_before']:,} → {rc['rel_tokens_after']:,} tokens "
              f"({rc['books_kept']}/{rc['books_total']} books).")
        elif rc:
            A(f"**Religious cap**: not triggered (Bib La {rc.get('rel_tokens',0):,} "
              f"≤ cap {rc.get('cap',0):,} tokens).")
        A("")

    # VOA actuals
    A("## VOA Nouvèl — crawl actuals")
    A("")
    if voa:
        c = voa["counts"]
        py = voa.get("pub_years", {})
        A(f"- Crawled **{voa['cursor']:,} / 39,286** sitemap URLs (descending id, "
          f"newest-first; resumable).")
        A(f"- **{c['article_pd_clean']:,} PD-clean articles kept**; dropped "
          f"{c['wire']:,} wire (AFP/AP/Reuters), {c['non_article']:,} audio/video "
          f"program pages, {c['topic_redirect']:,} topic-redirect stubs.")
        if c['article_pd_clean'] + c['wire']:
            wr = c['wire'] / (c['article_pd_clean'] + c['wire'])
            A(f"- Wire-drop rate: **{wr:.0%}** of text articles.")
        if py:
            A(f"- Publication years in the kept slice: "
              f"{', '.join(f'{y}:{n}' for y, n in sorted(py.items()) if y != 'unknown')}.")
        A("- Newest articles are held out as **authored_eval_v2** (temporal, never trained).")
        if voa['cursor'] < 39286:
            A(f"- **Partial slice** — the crawl is checkpointed/**resumable** "
              f"(`data/voa/crawl_state.json`); a full pass is ~12 h at ~1 req/s. "
              f"Recorded exactly what is in; a fuller VOA slice = resume + rebuild.")
    else:
        A("*(crawl state not found)*")
    A("")

    # fineweb verdict
    A("## fineweb-2 hat — net-new verdict")
    A("")
    if fw0:
        A(f"Ingested the survivors: raw {_m(fw0['raw_tokens_kb'])} → "
          f"**net-new {_m(fw0['net_new_tokens_kb'])} kreyol-bpe** "
          f"({fw0['net_new_frac_of_raw_tokens']:.0%} of raw; only "
          f"{fw0['dedup_dropped_docs']/fw0['raw_docs']:.0%} doc-overlap with v0.1). "
          f"The survey's \"heavy MADLAD overlap\" expectation was **refuted** — "
          f"fineweb-2 is a large NEW web-crawl source. Held at mix weight 1× "
          f"(volume, same register as MADLAD; does not inflate the authored share).")
    A("")

    # federal harvest
    A("## Federal PDF harvest (J2)")
    A("")
    if fed:
        A(f"Ingested **{fed['ingested_docs']} docs** "
          f"({fed['total_chars']:,} chars) across producers; IRS Pub 850 pairs "
          f"mined: **{fed['irs_pub850_pairs']}**.")
        A("")
        A("| producer | docs | chars | failed |")
        A("|---|--:|--:|--:|")
        for prod, pp in sorted(fed.get("per_producer", {}).items()):
            A(f"| {prod} | {pp['docs']} | {pp['chars']:,} | {pp['failed']} |")
        A("")
        A("Spot-check samples (first per producer) are recorded in "
          "`federal_stats.json`. Registers: health / immigration / tax / disaster / "
          "financial / government (17 U.S.C. §105 public domain).")
    else:
        A("*(federal harvest not yet run — awaiting the verified URL list from J2 "
          "discovery)*")
    A("")

    # family outcomes
    A("## Family-contributed set (J3) — per-file outcomes")
    A("")
    if fam:
        A("| file | verdict | outcome |")
        A("|---|---|---|")
        f = fam["files"]
        A(f"| CFPB glossary | {f['cfpb_glossary_family']['verdict']} | "
          f"train + **{f['cfpb_glossary_family']['pairs']} EN↔HT pairs** → committable federal pairs |")
        A(f"| NJ court glossary | {f['nj_court_glossary']['verdict']} | "
          f"EVAL-ONLY legal probe pool ({f['nj_court_glossary']['probe_terms']} terms) |")
        A(f"| MA DESE IEP | {f['ma_dese_iep']['verdict']} | "
          f"EVAL-ONLY education probe pool ({f['ma_dese_iep']['probe_labels']} labels) |")
        au = f['bmc_clinical_glossary']['orthography_audit']
        A(f"| BMC clinical glossary | {f['bmc_clinical_glossary']['verdict']} | "
          f"EVAL-ONLY; **{au['fr_accent_word_frac']:.1%} French-accent words** → "
          f"tagged nonstandard_orthography |")
        A(f"| FILE_7167 | {f['family_file_7167']['verdict']} | "
          f"producer **{f['family_file_7167']['producer_identified']}** — not extracted |")
        A(f"| Freeman dictionary | {f['freeman_medical_dictionary']['verdict']} | not opened |")
        A("")
        A("Contributor chain-of-custody: `corpus/contributors/family-contributor-1.md`.")
    A("")

    # red flags
    A("## Red flags / walls encountered")
    A("")
    A("- **VOA net-new (~2.25M) tripped the J0 red-flag gate** (< 5M). Proceeded "
      "under the user's \"Full v0.2 + mix control\" decision — see "
      "[corpus_v0_2_scoping.md](corpus_v0_2_scoping.md).")
    A("- **VOA is a broadcast outlet:** ~46% of `/a/` URLs are audio/video, ~34% of "
      "text articles are wire (dropped) — the crawl yield is bounded accordingly.")
    A("- **Bloom (sil-ai/bloom-lm)** remains **gated** (auto-grant, pending one "
      "click on the user's HF account); not yet ingested.")
    A("- No robots.txt wall hit (VOA `/a/` allowed; federal sites public).")
    A("")

    # nutrition label v2
    A("## Nutrition label v2")
    A("")
    if bs:
        comp = bs["composition_by_register"]
        A("| axis | value |")
        A("|---|---|")
        A(f"| Total unique tokens (kreyol-bpe) | {bs['total_tokens_kb']:,} |")
        A(f"| Documents | {bs['total_docs']:,} |")
        A(f"| Net-new vs v0.1 | {bs['new_survivor_tokens_kb']:,} |")
        A(f"| Registers | {len(comp)} ({', '.join(sorted(comp))}) |")
        wc = comp.get("web_crawl", {}).get("tokens", 0)
        A(f"| Web-crawl share (raw) | {wc/bs['total_tokens_kb']:.1%} |")
        A(f"| Authored/register share (raw) | {1-wc/bs['total_tokens_kb']:.1%} |")
        A(f"| Religious cap | ≤{C2.RELIGIOUS_CAP_FRAC:.0%} enforced |")
        A(f"| Eval axes added | authored_eval_v2 (VOA temporal) + NJ/MA/BMC terminology probes |")
        A("")
        A("**Honest caveat:** the large raw web-crawl share is by design (Pile-B "
          "volume for a data-limited model). The authored *voice* target is served "
          "by the mix weights + the register tail, not by raw composition. A true "
          "30%-authored-by-composition corpus needs permission-route sources "
          "(AKA/Ayibopost/Healthy Roads), out of this workstream's clean-rights scope.")
    A("")

    # reproduce
    A("## Reproduce")
    A("")
    A("```bash")
    A("cd ml && uv sync")
    A("uv run python -m corpus.corpus_index build")
    A("uv run python -m corpus.voa_crawl            # J1 (resumable; hours)")
    A("uv run python -m corpus.family               # J3")
    A("uv run python -m corpus.federal_pdfs harvest # J2 (after discovery)")
    A("uv run python -m corpus.small_wins all       # J4 Bib La / Konst / Storybooks")
    A("uv run python -m corpus.fineweb_ingest       # J4 fineweb survivors")
    A("uv run python -m corpus.build_v0_2           # J6b assemble")
    A("uv run python -m corpus.report_v0_2          # this report")
    A("```")
    A("")
    A("Nothing under `ml/data/` is committed; the mined federal glossary pairs and "
      "the contributor record are the only new committable data artifacts.")

    text = "\n".join(L)
    out = os.path.join(config.REPORTS, "corpus_v0_2.md")
    os.makedirs(config.REPORTS, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(text)
    common.log(f"  wrote {out}")
    return out


if __name__ == "__main__":
    build()
