"""Render ml/reports/corpus_v0_2_scoping.md from the J0 measurement sidecars.

Repo convention (edit-the-template-not-the-output): this Python string-builder IS
the template; re-run it to regenerate the report. Reads data/interim/j0/*.json.

Run:  uv run python -m corpus.report_v0_2_scoping
"""

from __future__ import annotations

import json
import os

from . import common, config, j0_scoping

RED_FLAG_MIN_NET_NEW = 5_000_000     # kreyol-bpe tokens (docs/data.md J0)
WIRE_INFEASIBLE = 0.40               # >40% of articles => clean filtering infeasible


def _try(name):
    p = os.path.join(j0_scoping.J0_DIR, name)
    if os.path.exists(p):
        with open(p, encoding="utf-8") as f:
            return json.load(f)
    return None


def _m(x):
    return f"{x/1e6:.2f}M"


def build():
    voa = _try("voa_sample.json")
    ov = _try("voa_madlad_overlap.json")
    fw = _try("fineweb2.json")
    bloom = _try("bloom.json")

    L = []
    A = L.append

    A("# Corpus v0.2 — J0 scoping pass (measure before crawling)")
    A("")
    A("*Workstream J0. Generated by `ml/corpus/report_v0_2_scoping.py` from the "
      "measurement sidecars under `data/interim/j0/` (untracked). Token unit is "
      "**kreyol-bpe** (the training tokenizer — the same unit as the \"112M unique "
      "tokens\" v0.1 figure); o200k is shown alongside where it matters. Spec: "
      "[../../docs/data.md](../../docs/data.md) §1–§2.*")
    A("")
    A("## The binding red-flag gate")
    A("")
    A("docs/data.md J0 sets a **STOP-and-report** gate before the multi-hour VOA "
      "crawl (J1) and the rest of the workstream:")
    A("")
    A("> STOP after J0 if any of: **VOA measured net-new < 5M tokens**, or the "
      "**wire-content rate makes clean filtering infeasible (>40% of articles)**, "
      "or **robots.txt blocks the crawl**.")
    A("")

    # ---- determination banner (computed) ----
    if voa and ov:
        gross_kb = voa["agg"]["gross_projection_kb"]
        gross_o2 = voa["agg"]["gross_projection_o200k"]
        tov = ov["overlap_rate_tokens"]
        net_kb = gross_kb * (1 - tov)
        net_o2 = gross_o2 * (1 - tov)
        wire = voa["agg"]["rates"]["wire_byline_rate_of_articles"]
        net_flag = net_kb < RED_FLAG_MIN_NET_NEW
        wire_flag = wire > WIRE_INFEASIBLE
        verdict = "**RED FLAG — STOP after J0**" if (net_flag or wire_flag) else "PASS"
        A(f"### Determination: {verdict}")
        A("")
        A(f"| Criterion | Threshold | Measured | Trips? |")
        A(f"|---|---|--:|:--:|")
        A(f"| VOA net-new tokens | ≥ 5M | **{_m(net_kb)} kreyol-bpe** ({_m(net_o2)} o200k) | "
          f"{'🚩 **YES**' if net_flag else 'no'} |")
        A(f"| Wire-content rate | ≤ 40% of articles | {wire:.1%} | "
          f"{'🚩 YES' if wire_flag else 'no'} |")
        A(f"| robots.txt | must allow `/a/` | allows (no crawl-delay) | no |")
        A("")
        A(f"VOA — the survey's *one big unlock* for **authored journalism** — "
          f"delivers only **~{_m(net_kb)} net-new kreyol-bpe tokens**, not the "
          f"estimated 20–60M. The *authored-share* premise of v0.2 does not survive "
          f"measurement. A separate surprise cuts the other way: **fineweb-2 hat is "
          f"far larger than the survey assumed** (§2) — real volume, but the same "
          f"web-crawl register. The two findings pull in opposite directions; see "
          f"§5 for what it means and the recommendation.")
        A("")

    # ---- VOA section ----
    if voa:
        a = voa["agg"]
        c, r = a["counts"], a["rates"]
        A("## 1. VOA Nouvèl (voanouvel.com)")
        A("")
        A("**robots.txt** (fetched 2026-07-23): article paths `/a/` are **allowed** "
          "(Disallow covers only /z/, /tv/, /radio/, /schedule/, search, comments, "
          "embeds, podcast sublinks). No `Crawl-delay` → we self-impose ~1 req/s. "
          "Cloudflare-fronted; normal browser headers suffice (a naive fetch 403s).")
        A("")
        A(f"**Sitemap enumeration.** Two gzipped article shards "
          f"(`sitemap_413_1/2.xml.gz`) list **{a['sitemap_total_urls']:,} article "
          f"URLs**, all under `/a/`, spanning **2002 → 2026-07** (by `lastmod`). "
          f"A small block of the newest IDs (~150) 302-redirect to a topic page and "
          f"are skipped.")
        A("")
        A(f"**Sample.** Stratified-by-year sample of **{a['sample_size']} URLs** "
          f"(seed {a.get('seed')}), fetched at ~1 req/s and extracted "
          f"(headline + `div.intro` lede + `div.wsw` body).")
        A("")
        A("### The article funnel (why 39k URLs ≠ 39k articles)")
        A("")
        A("| stage | sample | rate | projected on 39,286 URLs |")
        A("|---|--:|--:|--:|")
        A(f"| sitemap URLs | {a['sample_size']} | 100% | {a['sitemap_total_urls']:,} |")
        A(f"| — live **text** articles | {c['article']} | {r['live_article_rate']:.1%} | "
          f"~{round(a['sitemap_total_urls']*r['live_article_rate']):,} |")
        A(f"| — of which **wire** (AFP/AP/Reuters, dropped) | {c['article_wire_byline']} | "
          f"{r['wire_byline_rate_of_articles']:.1%} of articles | — |")
        A(f"| — **PD-clean** articles (kept) | {c['article_pd_clean']} | "
          f"{r['pd_clean_rate_of_urls']:.1%} of URLs | "
          f"~{round(a['sitemap_total_urls']*r['pd_clean_rate_of_urls']):,} |")
        A("")
        A(f"The other **{1 - r['live_article_rate']:.0%} of "
          f"`/a/` URLs are non-text**: daily radio program pages (*Pwogram maten / "
          f"mitan / aprè-midi*, *Bonjou Ayiti*, *Randevou-Radyo*, *Edisyon Maten*) "
          f"and video clips — VOA Nouvèl is a broadcast outlet, so roughly half its "
          f"article URLs carry an audio/video player and no prose body.")
        A("")
        A(f"**Wire carve-out.** {r['wire_byline_rate_of_articles']:.1%} of text "
          f"articles are bylined to a wire agency (AFP, AP=Associated Press, "
          f"Reuters) — licensed material, **not** VOA public domain — and are "
          f"dropped whole. (Editorial *mentions* of a wire agency in VOA-written "
          f"copy are correctly kept; only the byline triggers the drop.)")
        A("")
        A(f"**Length.** PD-clean articles are short: mean "
          f"**{a['tokens_per_article_kb']['mean']:.0f}** / median "
          f"{a['tokens_per_article_kb']['median']} kreyol-bpe tokens "
          f"(max {a['tokens_per_article_kb']['max']}).")
        A("")
        if ov:
            A(f"**MADLAD overlap.** MADLAD (Common Crawl) already scraped "
              f"voanouvel.com, so **{ov['overlap_rate_docs']:.1%} of PD-clean "
              f"articles ({ov['overlap_rate_tokens']:.1%} of their tokens) "
              f"near-duplicate documents already in v0.1** "
              f"(MinHash 5-gram, Jaccard ≥ 0.8; n={ov['articles_checked']}).")
            A("")
            A("### Net-new projection")
            A("")
            A("| unit | gross PD-clean | − MADLAD overlap | **net-new** |")
            A("|---|--:|--:|--:|")
            A(f"| kreyol-bpe | {_m(gross_kb)} | {tov:.1%} | **{_m(net_kb)}** |")
            A(f"| o200k | {_m(gross_o2)} | {tov:.1%} | **{_m(net_o2)}** |")
            A("")
            A(f"Even at the sample's 95% CI upper bound the net-new stays under 5M. "
              f"**VOA ≈ {_m(net_kb)} net-new kreyol-bpe tokens of authored "
              f"journalism** — real and register-unique, but ~10–25× below estimate.")
            A("")

    # ---- fineweb section ----
    A("## 2. fineweb-2 `hat_Latn`")
    A("")
    if fw:
        A(f"Streamed the full `hat_Latn` train split (**{fw['raw_docs']:,} docs / "
          f"{_m(fw['raw_tokens_kb'])} kreyol-bpe tokens raw**), then applied the "
          f"standing langid + junk filters and MinHash-deduped against v0.1:")
        A("")
        A("| gate | docs dropped | note |")
        A("|---|--:|---|")
        A(f"| langid (fineweb hat score < 0.65) | {fw['langid_dropped_docs']:,} | |")
        A(f"| junk fingerprints | {fw['junk_dropped_docs']:,} | {fw.get('junk_reasons', {})} |")
        A(f"| MinHash dup vs v0.1 | {fw['dedup_dropped_docs']:,} | MADLAD overlap |")
        A(f"| **net-new** | — | **{fw['net_new_docs']:,} docs / "
          f"{_m(fw['net_new_tokens_kb'])} kreyol-bpe** "
          f"({fw['net_new_frac_of_raw_tokens']:.0%} of raw) |")
        A("")
        A("**This contradicts the survey.** docs/data.md expected \"heavy MADLAD "
          "overlap … not new volume\"; measured, only **16.9% of docs** dedup "
          "against v0.1 and **68% of raw tokens survive** as net-new. MADLAD-400 "
          "(2023 snapshots) and fineweb-2 (through 2024, different extraction/dedup) "
          "share few *text*-level near-duplicates even where source URLs overlap, so "
          f"fineweb-2 is a **large new web-crawl source (~{_m(fw['net_new_tokens_kb'])} "
          "kreyol-bpe)** — nearly double the whole v0.1 corpus. Caveat: MinHash "
          "measures text near-dup, so this is net-new *text*; semantically it is the "
          "same translationese web register as MADLAD, not a new register.")
    else:
        A("*(measurement pending — sidecar `fineweb2.json` not yet written)*")
    A("")

    # ---- bloom section ----
    A("## 3. Bloom Library (`sil-ai/bloom-lm` hat)")
    A("")
    if bloom:
        A(f"260 hat stories. Per-entry license split (keep BY / BY-SA, drop NC/ND):")
        A("")
        A("| license | docs | kreyol-bpe tokens | verdict |")
        A("|---|--:|--:|:--:|")
        for lic, g in bloom["by_license"].items():
            A(f"| {lic} | {g['docs']} | {g['tokens']:,} | "
              f"{'**KEEP**' if g['keeper'] else 'drop'} |")
        A(f"| **keepers** | **{bloom['keeper_docs']}** | **{bloom['keeper_tokens_kb']:,}** | |")
        A("")
    else:
        A("**Gated (auto-grant).** The dataset requires agreeing to share contact "
          "info; the token account has not yet accepted. Access is auto-granted on "
          "one click at huggingface.co/datasets/sil-ai/bloom-lm — **pending a click "
          "on the user's HF account** (the browser session was not connected during "
          "J0). Structure confirmed from the public card: fields `text`/`license`/"
          "`title`; 260 hat stories; licenses cc-by-4.0 / cc-by-nc-4.0 / cc-by-nd-4.0 "
          "/ cc-by-sa. Keeper count + tokens will be finalized once access is "
          "granted (`corpus/j0_bloom.py` is ready to run).")
    A("")

    # ---- est vs measured table ----
    A("## 4. Estimate vs measured (docs/data.md §1)")
    A("")
    A("| source | docs/data.md estimate | measured (J0) | status |")
    A("|---|---|---|---|")
    if voa and ov:
        A(f"| **VOA Nouvèl** | ~20–60M | **~{_m(net_kb)} net-new** "
          f"(gross {_m(gross_kb)}; 54% articles, 34% wire, 45% MADLAD-dup) | "
          f"🚩 ~10–25× below est |")
    if fw:
        A(f"| fineweb-2 hat | ~300MB raw, *heavy overlap expected* | "
          f"raw {_m(fw['raw_tokens_kb'])}, **net-new {_m(fw['net_new_tokens_kb'])}** | "
          f"🚩 refutes overlap claim |")
    if bloom:
        A(f"| Bloom hat (BY/BY-SA) | ~50–100k | {bloom['keeper_tokens_kb']:,} keepers | measured |")
    else:
        A("| Bloom hat (BY/BY-SA) | ~50–100k | pending gated access | deferred |")
    A("| Federal PDFs (CDC/USCIS/IRS/…) | ~1–5M | not measured in J0 (→ J2) | estimate |")
    A("| IRS Pub 850 / CFPB glossary | ~80–160k | not measured in J0 (→ J2/J3) | estimate |")
    A("| Bib La 1985 | ~1M | not measured in J0 (→ J4) | estimate (cap ≤2%) |")
    A("| Konstitisyon 1987 | ~20–60k | not measured in J0 (→ J4) | estimate |")
    A("| Storybooks Haiti | ~10–15k | not measured in J0 (→ J4) | estimate |")
    A("| Tatoeba / disaster SMS | negligible | — | seed/eval only |")
    A("")

    # ---- what it means ----
    A("## 5. What this means for v0.2")
    A("")
    if voa and ov:
        fw_net = fw['net_new_tokens_kb'] if fw else 0
        A("The measured net-new splits into two piles that serve **opposite** goals:")
        A("")
        A("**Pile A — authored / register (the stated v0.2 thesis), small.**")
        A(f"- VOA authored journalism: **~{_m(net_kb)}**")
        A("- federal PDFs (health/legal/tax) + Bib La + Konstitisyon + Bloom + "
          "Storybooks: low single-digit millions combined (estimates; "
          "translation/religious/children's registers)")
        A("")
        A("This pile is only a few million tokens, so it **cannot** triple the "
          "authored share to 30% or reach 150–180M. What it *does* buy is real and is "
          "exactly what v0.1 lacks: **register diversity** — journalism, health, "
          "legal, tax, children's registers the model has never seen — plus a genuine "
          "**authored-journalism eval axis** (`authored_eval_v2` from a held-out VOA "
          "temporal slice), which also closes the standing fertility-report "
          "translated-vs-authored TODO.")
        A("")
        A(f"**Pile B — raw volume (not in the thesis), large and surprising.**")
        A(f"- fineweb-2 hat survivors: **~{_m(fw_net)} net-new kreyol-bpe** "
          f"(~{_m(fw['net_new_tokens_o200k']) if fw else '?'} o200k) — nearly double "
          f"the whole v0.1 corpus.")
        A("")
        A("Model C v0 is **data-limited** (112M unique tokens, trained ~6.7 epochs). "
          "Pile B would roughly triple the unique-token budget (112M → ~220M+), "
          "letting a next Model C train far longer before repeating — a real "
          "scale win the survey wrote off. **But** it is more of the same "
          "translationese web-crawl register: dropping it into the corpus raw would "
          "push web-crawl dominance from ~92% toward ~96% and *lower* the authored "
          "share (8% → ~4–5%). It serves model *scale*, not corpus *quality*, and the "
          "two goals fight over it.")
        A("")
        A("The clean way to hold both: ingest everything **register-tagged**, and "
          "drive the authored/register emphasis through the **training-mix weights** "
          "(upweight authored, cap web-crawl) rather than through what is physically "
          "in the corpus — the Micro-fleet Q2 (authored upweighting) knob. Caveat: "
          "even with upweighting, a ~2.5M authored pool can only be pushed to a high "
          "mix share by **repeating** it many times per epoch (overfit risk), so a "
          "true 30% authored target still needs a bigger authored source "
          "(permission-route).")
        A("")
        A("### Recommendation")
        A("")
        A("Per the gate, J0 **stops here and reports** rather than auto-proceeding on "
          "the old premise. The decision is the user's. The honest options:")
        A("")
        A("1. **Build a register-tagged v0.2, control quality via the mix "
          "(recommended).** Ingest VOA + federal + small authored wins **and** "
          "fineweb-2's ~108M, every doc tagged by origin/register. The corpus then "
          "serves *both* a bigger data-limited Model C (Pile B volume) and a "
          "register/authored emphasis (Pile A, upweighted at train time). Report the "
          "raw composition honestly (authored ~4–5% raw) and the target mix weights "
          "— do not claim 30%-by-composition.")
        A("2. **Register-only v0.2 (quality purist).** Ingest Pile A only; "
          "**exclude/cap fineweb-2** to avoid diluting the register. ~117–120M "
          "unique, authored ~10–12%, maximal register signal per token. Forgoes the "
          "volume win.")
        A("3. **Widen the rights net first.** Revisit PERMISSION-ROUTE / contested "
          "sources (Healthy Roads, AKA, Ayibopost, NYC/Boston, Florida, MIT-Haiti) — "
          "the only path that actually reaches ~30% *authored* — before committing.")
        A("4. **Defer v0.2.** Hold at v0.1 if neither the volume nor the register "
          "value justifies the effort now.")
        A("")
        A("The mechanical gate (VOA net-new < 5M) is genuinely tripped and the "
          "authored-unlock thesis is refuted; but fineweb-2 reframes the question "
          "from *\"is there enough authored data?\"* (no) to *\"do we want a "
          "bigger web-crawl base and/or a register-diverse tail?\"* (a design "
          "choice). That choice is why this stops for a human decision.")
        A("")

    # ---- reproduce ----
    A("## Reproduce")
    A("")
    A("```bash")
    A("cd ml && uv sync")
    A("uv run python -m corpus.corpus_index build          # near-dup index over v0.1")
    A("uv run python -m corpus.j0_scoping voa --n 200       # VOA stratified sample")
    A("uv run python -m corpus.j0_scoping overlap           # VOA↔v0.1 MinHash overlap")
    A("uv run python -m corpus.j0_scoping fineweb           # fineweb-2 net-new")
    A("uv run python -m corpus.j0_scoping bloom             # after HF gate accepted")
    A("uv run python -m corpus.report_v0_2_scoping          # this report")
    A("```")
    A("")
    A("Sitemap, sample, overlap, and fineweb numbers are pinned in the sidecars "
      "under `data/interim/j0/`. Nothing under `ml/data/` is committed.")

    text = "\n".join(L)
    out = os.path.join(config.REPORTS, "corpus_v0_2_scoping.md")
    os.makedirs(config.REPORTS, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(text)
    common.log(f"  wrote {out}")
    return out


if __name__ == "__main__":
    build()
