"""Phase-1 Workstream E — generate ml/reports/corpus_v0_1.md.

Reads the junk-stage + eval-slice stats sidecars and renders the v0.1 report:
size deltas (4 units), per-filter removal counts, the audit-label calibration
(the honest precision/recall story), the standing eval-slice definitions, and the
checkpoint-prompt DRAFT. No document text is emitted.

Run:  python -m corpus.report_v0_1 [--sample]
"""

from __future__ import annotations

import argparse
import csv
import json
import os

from . import common, config
from . import config_v0_1 as CV
from . import junk as J


def _load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _pct(a, b):
    return (100 * a / b) if b else 0.0


def _row(label, u, ref=None):
    """A 4-unit table row; if ref given, also show % of ref."""
    cells = [f"{u['docs']:,}", f"{u['bytes']:,}", f"{u['chars']:,}",
             f"{u['words']:,}", f"{u['tokens']:,}"]
    if ref is not None:
        cells.append(f"{_pct(u['tokens'], ref['tokens']):.2f}%")
    return f"| {label} | " + " | ".join(cells) + " |"


def _calibration(sample):
    """Recompute the filters' behaviour on the 200 human-verified audit docs:
    the key claim is ZERO natural false-positives. Reads audit_sample.jsonl (local,
    git-ignored) for text; emits only aggregate counts."""
    audit_text = os.path.join(config.REPORTS, "audit_sample.jsonl")
    if not os.path.exists(audit_text):
        return None
    labels = {}
    with open(CV.AUDIT_MODEL_LABELS, encoding="utf-8") as f:
        for r in csv.DictReader(f):
            labels[r["doc_id"]] = r
    docs = {}
    for line in open(audit_text, encoding="utf-8"):
        line = line.strip()
        if not line:
            continue
        d = json.loads(line)
        did = d.get("doc_id") or d.get("acquisition", {}).get("doc_id")
        docs[did] = d.get("text", "")
    crawl = [did for did in labels
             if labels[did]["source"] == "madlad_400_ht_clean" and did in docs]
    JUNK = [d for d in crawl if labels[d]["model_quality"] == "junk"]
    NAT = [d for d in crawl if labels[d]["model_quality"] == "ok"
           and labels[d]["model_translation_shaped"] == "natural"]
    TRANS = [d for d in crawl if labels[d]["model_translation_shaped"] == "translated"]
    hit = [d for d in crawl if J.junk_reason(docs[d], "crawl") is not None]
    return {
        "n_crawl": len(crawl), "n_junk": len(JUNK), "n_natural": len(NAT),
        "n_translated": len(TRANS), "hits": len(hit),
        "junk_caught": sum(1 for d in hit if d in JUNK),
        "natural_fp": sum(1 for d in hit if d in NAT),
        "translated_caught": sum(1 for d in hit if d in TRANS),
    }


def build(sample: bool) -> str:
    tag = common.run_tag(sample)
    js = _load(CV.JUNK_STATS.format(tag=tag))
    es = _load(CV.EVAL_SLICE_STATS.format(tag=tag))
    cal = _calibration(sample)
    v0, v01, rm = js["v0_total"], js["v0_1_total"], js["removed_total"]

    L = []
    A = L.append
    A("# Corpus v0.1 — junk-filtered + standing eval slices (Workstream E)")
    A("")
    A(f"*Build snapshot {CV.SNAPSHOT_DATE}. Generated by `ml/corpus/report_v0_1.py`. "
      f"v0.1 is a NEW pipeline stage layered on the frozen corpus-v0 shard — a "
      f"drop-only document subset, so corpus v0 stays byte-for-byte reproducible "
      f"([corpus_v0.md](corpus_v0.md)). See "
      f"[../../docs/phase-1.md](../../docs/phase-1.md) Workstream E and "
      f"[../../docs/plan.md](../../docs/plan.md) §3.2/§5.3.*")
    A("")
    A("## What changed from v0")
    A("")
    A(f"Corpus v0.1 removes **{rm['docs']:,} documents** "
      f"({_pct(rm['docs'], v0['docs']):.2f}% of docs, "
      f"{_pct(rm['tokens'], v0['tokens']):.2f}% of o200k tokens) that match the "
      f"audit's deterministic MT/CMS junk fingerprints. Every surviving document is "
      f"**byte-identical** to its v0 form (provenance + content hashes carry over). "
      f"Wikipedia bot-stubs stay **in**, flagged — their fate is fleet Q4's, not this "
      f"stage's.")
    A("")
    A(f"Reference tokenizer for token counts: `{js['reference_tokenizer']}` "
      f"(same unit as v0 and Workstream C).")
    A("")
    A("| corpus | docs | bytes | chars | ws words | o200k tokens | tok vs v0 |")
    A("|---|--:|--:|--:|--:|--:|--:|")
    A(_row("v0", v0, v0))
    A(_row("**v0.1**", v01, v0))
    A(_row("removed", rm, v0))
    A("")

    A("## Junk filters (deterministic, first-trip attribution)")
    A("")
    A("Each filter was **calibrated against the 200 human-verified audit labels** "
      "(the ground-truth set human-concurred in "
      "[audit_model_summary.md](audit_model_summary.md) §Human verification). The "
      "design target was **precision, not recall**: every rule fires on essentially "
      "zero human-labeled *natural* crawl docs.")
    A("")
    A("| filter | docs removed | bytes | chars | ws words | o200k tokens |")
    A("|---|--:|--:|--:|--:|--:|")
    for r, u in js["removed_by_reason_total"].items():
        A(f"| `{r}` | {u['docs']:,} | {u['bytes']:,} | {u['chars']:,} | {u['words']:,} | {u['tokens']:,} |")
    A(_row("**total removed**", rm))
    A("")
    A("Filter definitions (thresholds pinned in `corpus/config_v0_1.py`):")
    A("")
    A("- **`mt_placeholder`** — ≥2 `XNUMX`/`XNMX` occurrences. A WordPress/Babylon "
      "number-obfuscation artifact; the literal string is never real Kreyòl/English.")
    A("- **`commercial_spam`** — ≥3 *distinct* gambling/crypto/pharma/SEO-catalog "
      "markers (distinct-marker count, so one incidental `bitcoin` in a news story "
      "does not trip it).")
    A("- **`price_listing`** — ≥4 price patterns (`$`/`€`/`£`/`USD`/`HTG`/`Gourdes` + "
      "digits): product / price-list pages.")
    A("- **`html_entity`** — HTML entities (`&#39;`, `&quot;`, …) at ≥2.0 per 1000 "
      "chars and ≥3 total. **Near-absent** in the MADLAD *clean* split (it ships "
      "pre-stripped; v0's `normalize` does not decode entities, yet almost none "
      "survive) — kept as a rule because it is the audit's canonical CMS fingerprint, "
      "but it removes very little here.")
    A("- **`foreign_script`** — ≥20% non-Latin alphabetic chars (Kreyòl is "
      "Latin-script): Thai/Chinese-dominant scraped spam. **Crawl-only** — Kreyòl "
      "Wikipedia legitimately carries foreign-script names in authored stubs about "
      "foreign places/people, which are not junk.")
    A("")
    A("Evaluated and **dropped** as a rule: *untranslated-English-fragment density*. "
      "It fired on ~0 cleaned crawl docs and would false-positive on authored "
      "Kreyòl-Wikipedia bios of foreign figures (English/French proper-noun bodies) — "
      "documented, not applied.")
    A("")
    if cal:
        A("### Calibration on the human labels")
        A("")
        A(f"Running the applied filter set over the **{cal['n_crawl']} crawl audit "
          f"docs** ({cal['n_junk']} junk, {cal['n_natural']} natural, "
          f"{cal['n_translated']} translated by the human-concurred labels):")
        A("")
        A("| metric | value |")
        A("|---|--:|")
        A(f"| docs flagged | {cal['hits']} |")
        A(f"| **natural false-positives** | **{cal['natural_fp']} / {cal['n_natural']}** |")
        A(f"| junk caught | {cal['junk_caught']} / {cal['n_junk']} |")
        A(f"| translationese-commercial caught | {cal['translated_caught']} / {cal['n_translated']} |")
        A("")
    A("### The honest finding: the 17% junk is mostly not fingerprintable")
    A("")
    A("The machine audit put crawl **junk at ~17%** and crawl **translation-shaped at "
      "~70%** ([audit_model_summary.md](audit_model_summary.md)). These deterministic "
      "filters remove far less than 17% because that junk is overwhelmingly "
      "**semantic** — fluent-looking machine-translated commercial text (product "
      "blurbs, SEO articles) with no mechanical tell. What *is* fingerprintable — "
      "`XNUMX` placeholders, multi-marker spam, price catalogs, foreign-script scrapes "
      "— is a small, high-precision slice. Cranking thresholds down to chase 17% would "
      "start deleting authored Kreyòl, which the calibration above is designed to "
      "prevent. So v0.1 keeps the residual translationese in the training corpus and "
      "instead measures it: the `translation_shaped_eval` slice makes it a standing "
      "quality axis, and whether to filter it harder is **fleet Q3's** decision (v0 vs "
      "v0.1 at fixed compute), not an assumption baked in here.")
    A("")

    A("## Standing eval slices")
    A("")
    A(f"Two held-out quality axes carved from v0.1 (seed {es['seed']}), registered in "
      f"`splits.yaml`, **never trained on**. Membership = a human-verified **tier A** "
      f"core (the audit labels) + a conservative, documented **tier B** heuristic "
      f"expansion. Like the tokenizer_eval holdout, they are excluded by consumers "
      f"(training skips their doc_ids), not removed from the shard.")
    A("")
    A("| slice | tier | docs | bytes | chars | ws words | o200k tokens |")
    A("|---|---|--:|--:|--:|--:|--:|")
    for name in ("authored_eval", "translation_shaped_eval"):
        s = es["slices"][name]
        A(f"| `{name}` | A verified | {s['tier_a_verified']['docs']:,} | "
          f"{s['tier_a_verified']['bytes']:,} | {s['tier_a_verified']['chars']:,} | "
          f"{s['tier_a_verified']['words']:,} | {s['tier_a_verified']['tokens']:,} |")
        A(f"| | B heuristic | {s['tier_b_heuristic']['docs']:,} | "
          f"{s['tier_b_heuristic']['bytes']:,} | {s['tier_b_heuristic']['chars']:,} | "
          f"{s['tier_b_heuristic']['words']:,} | {s['tier_b_heuristic']['tokens']:,} |")
        A(f"| | **total** | **{s['total']['docs']:,}** | {s['total']['bytes']:,} | "
          f"{s['total']['chars']:,} | {s['total']['words']:,} | "
          f"**{s['total']['tokens']:,}** |")
    A("")
    A("**Membership rules:**")
    A("")
    A("- **`authored_eval`** (native-voice target) — tier A: audit docs the human "
      "concurred are `ht` / `ok` / `natural`. Tier B: non-bot-stub Wikipedia "
      f"(`wiki_bot_stub=false`), seeded-sampled, capped at "
      f"{es['caps']['authored_wiki_tier_b']} "
      f"(pool = {es['tier_b_pool_sizes']['authored_wiki_nonstub']:,} docs).")
    A("- **`translation_shaped_eval`** (contrast) — tier A: audit docs the human "
      "concurred are `translated` (all crawl). Tier B: crawl docs with a residual "
      "MT/CMS fingerprint too weak to be dropped as junk (≥1 HTML entity, or exactly "
      f"one `XNUMX`), seeded-sampled, capped at "
      f"{es['caps']['translation_heuristic_tier_b']} "
      f"(pool = {es['tier_b_pool_sizes']['crawl_residual_fingerprint']:,} docs).")
    A("")
    A("Disjoint by construction (natural vs translated labels are mutually exclusive; "
      "tier-B authored is Wikipedia-only, tier-B translationese crawl-only). Probe "
      "proverbs are absent from the corpus, so they cannot enter either slice. "
      "**Intended use:** a model whose `authored_eval` BPB falls faster than its "
      "`translation_shaped_eval` BPB is acquiring native voice, not just web-Kreyòl — "
      "the Station 5 nutrition-label axis and fleet Q2's measure.")
    A("")

    A("## Checkpoint prompt list — DRAFT (pending human sign-off)")
    A("")
    A("The ~10 fixed prompts run at **every** Model-C checkpoint forever — the "
      "\"watch it learn Kreyòl\" slider (Station 6) and the demoable base→chat "
      "transition (Station 2). **This is a DRAFT for the human to sign off; it is not "
      "frozen and is used for no metric.** It is an *exhibit-design* choice, made once "
      "with care (changing it later means re-running every kept checkpoint). The full "
      "draft is `corpus/checkpoint_prompts_DRAFT.json`.")
    A("")
    A("The proverb-completion slot is a **placeholder** — no probe-split proverb text "
      "is committed in any prompt set (Station-2 honesty: the model must not have "
      "trained on the proverb it is later tested on). The human fills it at freeze.")
    A("")
    draft = _load(CV.PROMPT_DRAFT_PATH)
    A("| # | category | prompt (draft) |")
    A("|--:|---|---|")
    for i, p in enumerate(draft["prompts_draft"], 1):
        prompt = p["prompt"].replace("|", "\\|")
        A(f"| {i} | {p['category']} | {prompt} |")
    A("")

    A("## Reproduce")
    A("")
    A("```bash")
    A("cd ml && uv sync")
    A("uv run python -m corpus.junk         # build corpus v0.1 (drop-only)")
    A("uv run python -m corpus.evalslices   # authored + translation-shaped slices")
    A("uv run python -m corpus.report_v0_1  # this report")
    A("```")
    A("")
    A(f"Input shard: `{js['input_shard']}` (corpus v0). Seeds: eval slices "
      f"{es['seed']}. Filter thresholds + spam markers pinned in "
      f"`corpus/config_v0_1.py`. Nothing under `ml/data/` is committed.")
    A("")

    text = "\n".join(L)
    out = os.path.join(config.REPORTS, "corpus_v0_1.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write(text)
    common.log(f"  report -> {out} ({len(text):,} chars)")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sample", action="store_true")
    args = ap.parse_args()
    build(args.sample)


if __name__ == "__main__":
    main()
