"""Generate the Workstream-G reports from the results JSONs written by g_run.py:

  f2_gates.md     — Part 2: gate-by-gate evidence.
  depth_sweep.md  — Part 3: sweep BPB table + depth pick + rationale.
  modelc_v0.md    — Part 4: learning curves, checkpoint story, vs-bases table, nutrition label.

Run:  python -m train.g_report {gates|sweep|modelc|all}
"""

from __future__ import annotations

import argparse
import json
import os

from . import config as F
from . import llama_config as G
from . import llama_model as M

REPORTS = os.path.join(F.REPO_ROOT, "reports")


def _load(name):
    p = os.path.join(G.G_WORK, name)
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None


def _w(path, lines):
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[g_report] wrote {path}")


# ============================ f2_gates.md =====================================

def gates_md():
    r = _load("g_gates_results.json")
    assert r, "no g_gates_results.json — run `g_run gate` first"
    g = r["gates"]
    A = []
    A.append("# F2 conversion gates — Model C (standard-Llama)")
    A.append("")
    A.append(f"*Snapshot {G.SNAPSHOT_DATE}. Throwaway **d16** checkpoint (`{g['tag']}` step {g['step']}), "
             f"trained only to exercise the deployment chain. llama.cpp pinned `{g['llama_cpp_commit'][:12]}`. "
             f"GPU: Modal {F.MODAL_GPU}. Generated by `train/g_report.py`. See "
             f"[../../docs/phase-1.md](../../docs/phase-1.md) Workstream G.*")
    A.append("")
    A.append("The Workstream-F finding was that nanochat's speedrun architecture had no llama.cpp "
             "graph (48% nanochat-only params) and its custom pre-tokenizer wasn't registered. Model C "
             "is now a **real `transformers.LlamaForCausalLM`**, so the architecture blocker is gone by "
             "construction; these gates prove the *rest* of the chain end-to-end.")
    A.append("")
    # verdict table
    def _pf(b):
        return "✅ pass" if b else "❌ fail"
    g1 = g["gate1_logits"]; g2 = g["gate2_gguf"]
    g4 = g.get("gate4_parity", {}); g3 = g.get("gate3_stock", {})
    g5 = g["gate5_onnx"]; g6 = g.get("gate6_cross_runtime", {})
    A.append("## Verdict")
    A.append("")
    A.append("| Gate | What it proves | Result |")
    A.append("|---|---|---|")
    A.append(f"| 1 native↔HF logits | export is lossless | {_pf(g1['pass'])} — fp32 round-trip Δ={g1['max_abs_logit_diff_fp32_roundtrip']:.1e}, bf16 Δ={g1['max_abs_logit_diff_fp32_vs_bf16']:.1e} |")
    A.append(f"| 2 GGUF + llama.cpp | converts & generates Kreyòl | {_pf(g2['final_rc'] == 0 and g2['gguf_exists'])} — rc={g2['final_rc']}, registered `kreyol-bpe`={g2['registered_kreyol_bpe']} |")
    if g4:
        p = g4["probe"]
        A.append(f"| 4 token-ID parity | tiktoken=HF=llama.cpp | {_pf(p['llamacpp_sentence_frac'] > 0.99 and g4['fixtures_all_match'])} — llama.cpp {p['llamacpp_sentence_frac']:.3f} / HF {p['hf_sentence_frac']:.3f} sentence-exact |")
    if g3:
        rej = g3.get("ollama_rejected_unknown_pretokenizer")
        A.append(f"| 3 stock Ollama | measured, not faked | {'⚠️ rejects (as predicted)' if rej else _pf(g3.get('ollama_loaded_and_generated'))} — see below |")
    A.append(f"| 5 ONNX browser | transformers.js path | {_pf(g5.get('export_ok') and g5.get('onnx_gen_ok'))} — export_ok={g5.get('export_ok')}, gen_ok={g5.get('onnx_gen_ok')} |")
    if g6:
        pre = g6.get("pre_quant", [])
        avg = round(sum(x["native_vs_llamacpp_lcp"] for x in pre) / len(pre), 3) if pre else None
        A.append(f"| 6 cross-runtime greedy | native=llama.cpp=ONNX | native↔llama.cpp LCP avg={avg} (pre-quant); Q4 looser |")
    A.append("")

    # gate 1
    A.append("## Gate 1 — native vs exported-HF logits")
    A.append("")
    A.append(g1["note"])
    A.append("")
    A.append(f"- fp32 reload round-trip max|Δlogit| = **{g1['max_abs_logit_diff_fp32_roundtrip']:.2e}** (lossless save/load).")
    A.append(f"- fp32 vs bf16 (deployment dtype) max|Δlogit| = **{g1['max_abs_logit_diff_fp32_vs_bf16']:.2e}**; argmax token agreement = **{g1['argmax_token_agree_fp32_vs_bf16']}**.")
    A.append("")

    # gate 2
    A.append("## Gate 2 — HF → GGUF → llama.cpp (patched)")
    A.append("")
    A.append(f"`convert_hf_to_gguf.py` first pass recognized our pre-tokenizer: "
             f"**{g2['first_pass_recognized_pretokenizer']}**. Harvested chkhsh "
             f"`{g2.get('harvested_chkhsh')}` → registered as `kreyol-bpe` in `conversion/base.py` "
             f"(the generic custom-tokenizer step). Final convert rc=**{g2['final_rc']}**, "
             f"GGUF **{g2['gguf_bytes']/1e6:.1f} MB**.")
    A.append("")
    if g2.get("llama_cpp_generation"):
        gen = g2["llama_cpp_generation"]
        A.append("Greedy generation from the patched `llama-cli` (proves the compiled binary loads our "
                 "`kreyol-bpe` pre-tokenizer and emits Kreyòl):")
        A.append("")
        A.append("```")
        A.append(gen["text"][-600:].strip())
        A.append("```")
        A.append("")

    # gate 4
    if g4:
        A.append("## Gate 4 — token-ID parity (tiktoken / HF / llama.cpp)")
        A.append("")
        p = g4["probe"]
        A.append(f"On the {p['n']}-line source-mixed probe (tiktoken = the rustbpe source of truth; "
                 f"HF leg full, llama.cpp leg on {p.get('llamacpp_n', '?')} lines — llama-tokenize "
                 f"reloads the GGUF per line):")
        A.append("")
        A.append("| pair | sentence-exact | token-level |")
        A.append("|---|--:|--:|")
        A.append(f"| HF tokenizer.json vs tiktoken | {p['hf_sentence_frac']:.4f} | {p['hf_token_frac']:.4f} |")
        A.append(f"| llama.cpp GGUF vs tiktoken | {p['llamacpp_sentence_frac']:.4f} | {p['llamacpp_token_frac']:.4f} |")
        A.append("")
        A.append("**Apostrophe / clitic / accent fixtures** (the cases a wrong pre-tokenizer mangles):")
        A.append("")
        A.append("| fixture | tiktoken n | HF match | llama.cpp match |")
        A.append("|---|--:|:--:|:--:|")
        for fx in g4["fixtures"]:
            A.append(f"| `{fx['text']}` | {len(fx['tiktoken'])} | {'✅' if fx['hf_match'] else '❌'} | "
                     f"{'✅' if fx['llamacpp_match'] else '❌'} |")
        A.append("")
        if p.get("divergence_examples"):
            A.append("First probe divergences (if any):")
            A.append("")
            A.append("```")
            for ex in p["divergence_examples"]:
                A.append(json.dumps(ex, ensure_ascii=False))
            A.append("```")
            A.append("")

    # gate 3
    if g3:
        A.append("## Gate 3 — stock Ollama (measured, not faked)")
        A.append("")
        if g3.get("ollama_bin"):
            cr = g3.get("ollama_create", {}); rn = g3.get("ollama_run", {})
            A.append(f"Stock Ollama (bundles stock llama.cpp) was given the `kreyol-bpe` GGUF via a "
                     f"`FROM` Modelfile. `ollama create` rc={cr.get('rc')}, `ollama run` rc={rn.get('rc')}. "
                     f"Rejected with *unknown pre-tokenizer*: **{g3.get('ollama_rejected_unknown_pretokenizer')}**; "
                     f"loaded+generated: **{g3.get('ollama_loaded_and_generated')}**.")
            A.append("")
            A.append("```")
            A.append((rn.get("tail") or cr.get("tail") or "").strip()[-700:])
            A.append("```")
            A.append("")
            A.append("This matches the llama.cpp source: an unrecognized `tokenizer.ggml.pre` **throws** "
                     "(`unknown pre-tokenizer type`), it does NOT silently fall back to GPT-2 — so a stock "
                     "runtime *refuses* the model rather than mis-tokenizing. The fix is the local "
                     "llama.cpp patch (gates 2/4/6 above use it); the upstream registration patch + parity "
                     "fixtures are prepared (`train/patch_llamacpp_cpp.py` + the converter chkhsh entry) but "
                     "**not** submitted — that PR is the human's to open.")
        else:
            A.append("_Ollama binary unavailable in the container; stock behavior is established from the "
                     "llama.cpp source (unrecognized pre-tokenizer throws)._")
        A.append("")
        if g3.get("gpt2_fallback_clitic_damage"):
            A.append("**Counterfactual GPT-2-fallback damage** (what a silent fallback *would* do to clitics — "
                     "the reason the registration matters):")
            A.append("")
            A.append("| fixture | kreyol_aware tokens | GPT-2-split pieces | differs |")
            A.append("|---|--:|--:|:--:|")
            for d in g3["gpt2_fallback_clitic_damage"]:
                A.append(f"| `{d['text']}` | {d['kreyol_aware_tokens']} | {d['gpt2_fallback_pieces']} | "
                         f"{'⚠️' if d['differs'] else '='} |")
            A.append("")

    # gate 5
    A.append("## Gate 5 — ONNX / transformers.js (offline browser path)")
    A.append("")
    if g5.get("export_ok"):
        A.append(f"Exported with `optimum` to ONNX ({', '.join(g5.get('onnx_files', [])[:8])}). "
                 f"onnxruntime greedy generation: **{g5.get('onnx_gen_ok')}**.")
        A.append("")
        if g5.get("onnx_completion"):
            A.append(f"> ONNX greedy completion: `{g5['onnx_completion'][:200]}`")
            A.append("")
        A.append(g5.get("note", ""))
    else:
        A.append(f"❌ export failed: {g5.get('export_error')}")
    A.append("")

    # gate 6
    if g6:
        A.append("## Gate 6 — cross-runtime greedy agreement")
        A.append("")
        A.append("Longest-common-prefix ratio of greedy continuations (1.0 = identical). Pre-quant we "
                 "expect agreement; Q4 gets the looser numerical check.")
        A.append("")
        A.append("| prompt | native↔llama.cpp LCP |")
        A.append("|---|--:|")
        for x in g6.get("pre_quant", []):
            A.append(f"| `{x['prompt'][:40]}` | {x['native_vs_llamacpp_lcp']} |")
        if "native_vs_onnx_lcp_first_prompt" in g6:
            A.append("")
            A.append(f"native↔ONNX LCP (first prompt) = **{g6['native_vs_onnx_lcp_first_prompt']}**.")
        if g6.get("q4"):
            A.append("")
            A.append("**Q4_K_M (looser check):**")
            A.append("")
            A.append("| prompt | Q4↔f16 LCP |")
            A.append("|---|--:|")
            for x in g6["q4"]:
                A.append(f"| `{x['prompt'][:40]}` | {x['q4_vs_f16_lcp']} |")
        A.append("")

    # artifacts + cost
    art = g.get("artifacts", {})
    A.append("## Artifacts")
    A.append("")
    A.append(f"- GGUF f16: {art.get('gguf_f16', {}).get('bytes', 0)/1e6:.1f} MB, sha256 `{art.get('gguf_f16', {}).get('sha256_16')}`")
    A.append(f"- GGUF Q4_K_M: {art.get('gguf_q4', {}).get('bytes', 0)/1e6:.1f} MB, sha256 `{art.get('gguf_q4', {}).get('sha256_16')}`")
    A.append("- ONNX export dir stored on the Modal Volume (transformers.js bundle).")
    A.append("")
    A.append("All artifacts live on the Modal Volume (nothing under `ml/data/` committed).")
    _w(os.path.join(REPORTS, "f2_gates.md"), A)


# ============================ depth_sweep.md ==================================

def _latency_note(depth):
    p = M.param_count(depth)["total"]
    return f"{p/1e6:.0f}M params → ~{depth} transformer blocks; CPU/browser decode latency scales ≈ linearly with depth"


def sweep_md():
    r = _load("g_sweep_results.json")
    assert r, "no g_sweep_results.json — run `g_run sweep` first"
    runs = r["runs"]
    A = []
    A.append("# Depth mini-sweep — Model C (d12 / d16 / d20)")
    A.append("")
    S = r["sweep_config"]
    tok = S["num_iterations"] * G.TOKENS_PER_STEP
    A.append(f"*Snapshot {G.SNAPSHOT_DATE}. Identical data order + budget: **{S['num_iterations']} steps × "
             f"{G.TOKENS_PER_STEP:,} tok/step = {tok/1e6:.0f}M tokens** each, seed {G.TRAIN['seed']}. "
             f"GPU: Modal {F.MODAL_GPU}. Generated by `train/g_report.py`.*")
    A.append("")
    A.append("Data-limited (112M unique tokens) + local-first: the pick is the depth where validation BPB "
             "stops improving enough to justify the per-token inference cost — not the largest model.")
    A.append("")
    A.append("| depth | params | median tok/s | final train loss | BPB general ↓ | BPB authored ↓ | BPB transl. |")
    A.append("|--:|--:|--:|--:|--:|--:|--:|")
    for d in S["depths"]:
        run = runs.get(f"d{d}")
        if not run:
            continue
        tr = run["train"]; bp = run["bpb"]
        gen = bp.get("general_holdout", {}).get("bpb")
        auth = bp.get("authored_eval", {}).get("bpb")
        trs = bp.get("translation_shaped_eval", {}).get("bpb")
        loss = tr["logs"][-1]["loss"] if tr.get("logs") else None
        A.append(f"| d{d} | {tr['params']/1e6:.0f}M | {tr.get('median_tok_s')} | {loss} | "
                 f"{gen:.4f} | {auth:.4f} | {trs:.4f} |" if gen else
                 f"| d{d} | {tr['params']/1e6:.0f}M | {tr.get('median_tok_s')} | {loss} | — | — | — |")
    A.append("")
    A.append("## Pick")
    A.append("")
    A.append("_(rationale filled from the numbers above — see the FINAL SUMMARY / phase-1.md G block.)_")
    A.append("")
    A.append("Latency context per depth:")
    for d in S["depths"]:
        A.append(f"- **d{d}**: {_latency_note(d)}.")
    _w(os.path.join(REPORTS, "depth_sweep.md"), A)


# ============================ modelc_v0.md ====================================

def modelc_md():
    r = _load("g_flagship_results.json")
    assert r, "no g_flagship_results.json — run `g_run flagship` first"
    base = _load("g_base_bpb.json")
    nutrition = _load("g_nutrition.json")
    tr = r["train"]
    ckpts = tr["checkpoints"]
    A = []
    A.append(f"# Model C v0 — d{r['depth']} Kreyòl-first base ({tr['params']/1e6:.0f}M)")
    A.append("")
    A.append(f"*Snapshot {G.SNAPSHOT_DATE}. Standard Llama, width 768, depth {r['depth']}. "
             f"Corpus v0.1 train split ({tr['unique_train_tokens']/1e6:.0f}M unique tokens); "
             f"{tr['effective_tokens']/1e6:.0f}M effective tokens = **{tr['epochs']} epochs**. "
             f"kreyol-bpe (24,576). GPU: Modal {F.MODAL_GPU}. Generated by `train/g_report.py`.*")
    A.append("")
    # learning curves
    A.append("## Learning curves (BPB per checkpoint)")
    A.append("")
    A.append("| tokens | step | general ↓ | authored ↓ | translation-shaped | FLORES hat |")
    A.append("|--:|--:|--:|--:|--:|--:|")
    for c in ckpts:
        b = c.get("bpb", {})
        def g(k):
            v = b.get(k)
            return f"{v:.4f}" if isinstance(v, (int, float)) else "—"
        A.append(f"| {c['tokens']/1e6:.0f}M | {c['step']} | {g('general_holdout')} | {g('authored_eval')} | "
                 f"{g('translation_shaped_eval')} | {g('flores_hat')} |")
    A.append("")
    # checkpoint story: generations
    A.append("## The checkpoint-by-checkpoint story (frozen prompt list)")
    A.append("")
    A.append("Greedy completions of the 10 frozen exhibit prompts, archived per checkpoint as the slider "
             "asset (`reports/modelc_v0_generations.json`). A few excerpts showing babble→Kreyòl:")
    A.append("")
    # pick 3 checkpoints: first, a middle, last
    show_steps = [ckpts[0], ckpts[len(ckpts) // 2], ckpts[-1]] if len(ckpts) >= 3 else ckpts
    for c in show_steps:
        A.append(f"**{c['tokens']/1e6:.0f}M tokens (step {c['step']})**")
        A.append("")
        for gsamp in (c.get("generations") or [])[:3]:
            A.append(f"- `{gsamp['prompt'][:40]}` → `{gsamp['completion'][:120]}`")
        A.append("")
    # vs bases
    if base:
        A.append("## Model C vs the base-model scorecard (same slices)")
        A.append("")
        A.append("BPB (↓) on the identical held-out texts — the 150M Kreyòl-first model vs the 3–4B "
                 "multilingual bases (Workstream D):")
        A.append("")
        A.append("| model | params | authored ↓ | general ↓ | translation-shaped |")
        A.append("|---|--:|--:|--:|--:|")
        final = ckpts[-1].get("bpb", {})
        A.append(f"| **Model C v0 (d{r['depth']})** | {tr['params']/1e6:.0f}M | "
                 f"{final.get('authored_eval', float('nan')):.4f} | {final.get('general_holdout', float('nan')):.4f} | "
                 f"{final.get('translation_shaped_eval', float('nan')):.4f} |")
        labels = {"google/gemma-3-4b-pt": "gemma-3-4b-pt", "Qwen/Qwen3-4B-Base": "Qwen3-4B-Base",
                  "meta-llama/Llama-3.2-3B": "Llama-3.2-3B"}
        params = {"google/gemma-3-4b-pt": "4B", "Qwen/Qwen3-4B-Base": "4B", "meta-llama/Llama-3.2-3B": "3B"}
        for repo, slices in base["bases"].items():
            def g(k):
                v = slices.get(k, {}).get("bpb")
                return f"{v:.4f}" if isinstance(v, (int, float)) else "—"
            A.append(f"| {labels.get(repo, repo)} | {params.get(repo, '?')} | {g('authored_eval')} | "
                     f"{g('general_holdout')} | {g('translation_shaped_eval')} |")
        A.append("")
    # nutrition label
    if nutrition:
        A.append("## Nutrition label v1")
        A.append("")
        A.append(_nutrition_block(nutrition, r))
    _w(os.path.join(REPORTS, "modelc_v0.md"), A)

    # also dump the full generations JSON (the committable slider asset)
    gens = {"snapshot_date": G.SNAPSHOT_DATE, "depth": r["depth"], "tag": r["tag"],
            "checkpoints": [{"step": c["step"], "tokens": c["tokens"],
                             "generations": c.get("generations", [])} for c in ckpts]}
    gp = os.path.join(REPORTS, "modelc_v0_generations.json")
    with open(gp, "w", encoding="utf-8") as f:
        json.dump(gens, f, indent=2, ensure_ascii=False)
    print(f"[g_report] wrote {gp}")


def _nutrition_block(n, r):
    L = []
    L.append("```")
    L.append(f"Model C v0 — d{r['depth']} ({r['train']['params']/1e6:.0f}M) Kreyòl-first base")
    L.append(f"  Tokenizer   : kreyol-bpe, 24,576 vocab (kreyol_aware pre-tokenization)")
    L.append(f"  Training    : corpus v0.1, {r['train']['unique_train_tokens']/1e6:.0f}M unique tokens, "
             f"{r['train']['epochs']} epochs ({r['train']['effective_tokens']/1e6:.0f}M effective)")
    comp = n.get("composition_by_origin", {})
    L.append("  Composition (by origin):")
    for k, v in comp.items():
        L.append(f"    {k:<22}: {v['pct']:.1f}%  ({v['docs']:,} docs)")
    genre = n.get("composition_by_genre", {})
    if genre:
        L.append("  Composition (by genre):")
        for k, v in sorted(genre.items(), key=lambda x: -x[1]["pct"])[:8]:
            L.append(f"    {k:<22}: {v['pct']:.1f}%")
    L.append(f"  Known gaps  : {n.get('known_gaps', '')}")
    L.append(f"  Audit rates : {n.get('audit_note', '')}")
    L.append("```")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("which", choices=["gates", "sweep", "modelc", "all"])
    args = ap.parse_args()
    if args.which in ("gates", "all"):
        gates_md()
    if args.which in ("sweep", "all"):
        sweep_md()
    if args.which in ("modelc", "all"):
        modelc_md()


if __name__ == "__main__":
    main()
