"""Output writers: the parity bar chart and the methodology report."""

from __future__ import annotations

import os

from . import config


def _short(label: str) -> str:
    if label.startswith("claude_api_input_parity"):
        return "Claude API\n(opus-4-8)"
    return label.split(" (")[0]


def write_png(rows, path: str, repo_root, log):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    ordered = sorted(rows, key=lambda r: r["parity_ht_en"])
    labels = [_short(r["label"]) for r in ordered]
    parity = [r["parity_ht_en"] for r in ordered]
    lo = [r["parity_ht_en"] - r["ci95_lo_ht_en"] for r in ordered]
    hi = [r["ci95_hi_ht_en"] - r["parity_ht_en"] for r in ordered]
    colors = ["#c1666b" if r["kind"] == "api" else "#4d648d" for r in ordered]

    fig, ax = plt.subplots(figsize=(max(7, 1.15 * len(ordered)), 5.0))
    x = range(len(ordered))
    ax.bar(x, parity, yerr=[lo, hi], capsize=4, color=colors, edgecolor="black", linewidth=0.5)
    ax.axhline(1.0, color="grey", linestyle="--", linewidth=1)
    ax.text(len(ordered) - 0.5, 1.01, "parity (1.0)", ha="right", va="bottom",
            color="grey", fontsize=8)
    for i, p in zip(x, parity):
        ax.text(i, p + max(hi) * 0.15 + 0.02, f"{p:.2f}", ha="center", va="bottom", fontsize=8)
    ax.set_xticks(list(x))
    ax.set_xticklabels(labels, rotation=35, ha="right", fontsize=8)
    ax.set_ylabel("Haitian Creole ÷ English tokens (parity)")
    ax.set_title("Kreyòl token tax on FLORES+ devtest (sum-based parity, 95% CI)\n"
                 f"n={rows[0]['n_sentences']} aligned sentences · {config.SNAPSHOT_DATE}",
                 fontsize=10)
    ax.set_ylim(0, max(r["ci95_hi_ht_en"] for r in ordered) * 1.18)
    fig.tight_layout()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fig.savefig(path, dpi=150)
    plt.close(fig)
    log(f"  wrote {os.path.relpath(path, repo_root)}")


def _fmt(v):
    return "—" if v == "" or v is None else v


def _authored_vs_translated_section(A, repo_root):
    """Renders the authored-vs-translated Kreyòl fertility result (closes the
    standing Workstream C TODO). Data from fertility.authored's sidecar, produced
    once Workstream J's authored_eval_v2 (VOA journalism) exists."""
    import json
    sidecar = os.path.join(repo_root, "ml", "data", "interim",
                           "fertility_authored.json")
    if not os.path.exists(sidecar):
        A("- **Authored-vs-translated fertility (Workstream J):** pending — run "
          "`corpus.build_v0_2` (writes `authored_eval_v2` from VOA journalism) then "
          "`python -m fertility.authored`. The template renders the result here once "
          "the sidecar exists.")
        return
    with open(sidecar, encoding="utf-8") as f:
        d = json.load(f)
    A("### Authored vs translated Kreyòl (Workstream J — TODO resolved)\n")
    A("FLORES's Haitian side is itself translated, so Workstream C could not compare "
      "authored vs translated fertility. Workstream J's held-out **VOA journalism** "
      "(`authored_eval_v2`) supplies a native-authored set. Tokens-per-byte "
      "(byte-normalized, cross-tokenizer comparable):\n")
    cs = d["counters"]
    A("| slice | kind | docs | " + " | ".join(f"{c} tok/byte" for c in cs) + " |")
    A("|---|---|--:|" + "|".join("--:" for _ in cs) + "|")
    for name, row in d["slices"].items():
        if not row.get("present"):
            continue
        cells = " | ".join(f"{row['tok_per_byte'][c]:.4f}" for c in cs)
        A(f"| {name} | {row['kind']} | {row['docs']} | {cells} |")
    A("")
    gaps = d.get("authored_minus_translated_tok_per_byte", {})
    if "authored_eval_v2" in gaps:
        g = gaps["authored_eval_v2"]["kreyol-bpe"]
        direction = ("LOWER — the tokenizer fits native journalism at least as well "
                     "as translationese (not overfit to translationese)") if g < 0 else \
                    ("higher — native journalism is denser for the tokenizer than "
                     "translationese web text")
        A(f"**Finding:** on `kreyol-bpe`, authored VOA journalism is "
          f"{abs(g):.4f} tok/byte {'below' if g < 0 else 'above'} translationese "
          f"({direction}).")
    A("")


def write_markdown(rows, petrov, flores, words, skipped, path, repo_root, log):
    d = config.SNAPSHOT_DATE
    L = []
    A = L.append

    A(f"# Tokenizer fertility for Haitian Creole — Workstream C\n")
    A(f"*Measurement snapshot: {d}. Generated by `ml/fertility/` — see "
      f"[../../docs/phase-0.md](../../docs/phase-0.md) (Workstream C) and "
      f"[../../docs/plan.md](../../docs/plan.md) §3.3.*\n")

    # headline
    tok_rows = [r for r in rows if r["kind"] == "tokenizer"]
    best = min(rows, key=lambda r: r["parity_ht_en"])
    worst = max(rows, key=lambda r: r["parity_ht_en"])
    A("## Headline\n")
    A(f"On {flores['n']} aligned FLORES+ `devtest` sentences, the same content costs "
      f"**{worst['parity_ht_en']:.2f}× more tokens in Haitian Creole than in English** on "
      f"`{_plain(worst['label'])}` and as little as **{best['parity_ht_en']:.2f}×** on "
      f"`{_plain(best['label'])}`. Full parity table below, with paired-bootstrap 95% CIs.\n")
    ours = next((r for r in rows if r["label"].startswith("kreyol-bpe")), None)
    if ours is not None:
        flips = ours["parity_ht_en"] < 1.0
        A(f"**Our Kreyòl tokenizer (`{_plain(ours['label'])}`, Workstream B) lands at ht/en parity "
          f"{ours['parity_ht_en']:.2f}× (95% CI [{ours['ci95_lo_ht_en']:.2f}, {ours['ci95_hi_ht_en']:.2f}]) "
          f"and ht/fr {ours['parity_ht_fr']:.2f}× ([{ours['ci95_lo_ht_fr']:.2f}, {ours['ci95_hi_ht_fr']:.2f}]).** "
          + ("It **flips the tax**: identical content now costs *fewer* tokens in Kreyòl than in "
             "English — the point of training a Kreyòl-first vocabulary.\n" if flips else
             "That is the lowest Kreyòl token tax of any tokenizer measured here — a Kreyòl-first "
             "vocabulary nearly erases the gap.\n"))
    known = {"cl100k", "NLLB", "kreyol-bpe"}  # Petrov-published (reproduced) + our own (obviously first)
    novel = [r["label"].split(" (")[0] for r in rows
             if r["kind"] == "tokenizer" and r["label"].split(" (")[0] not in known]
    A("**This extends Petrov et al. (2023)** ([arXiv:2305.15425](https://arxiv.org/abs/2305.15425)), "
      "who measured Haitian Creole through the cl100k-era tokenizers — our cl100k and NLLB rows "
      f"reproduce theirs. The new contribution is the post-2023 generation: **as of {d} we could "
      f"find no previously published Haitian-Creole parity numbers for "
      f"{', '.join(novel) if novel else 'the newer tokenizers'}, or any Claude API estimate** — "
      "those rows are, to our knowledge, first published here, alongside our own Kreyòl tokenizer. "
      "(\"First published we could find,\" not \"first-ever.\")\n")

    # step 1 — validation
    A("## Pipeline validation (Petrov et al. 2023)\n")
    A("Before measuring anything new, we reproduce Petrov et al.'s published Haitian/English "
      "`cl100k_base` parity from **their** released data with **our** counting code "
      "([tokenization-fairness]"
      f"(https://github.com/aleksandarpetrov/tokenization-fairness), pinned commit "
      f"`{config.PETROV_COMMIT[:12]}`).\n")
    A("| Source | ht tokens | en tokens | ht/en parity |")
    A("|---|--:|--:|--:|")
    A(f"| Petrov released totals (`tokenization_lengths.csv`) | {petrov['his_ht_tokens']} | "
      f"{petrov['his_en_tokens']} | **{petrov['his_csv_parity']:.4f}** |")
    A(f"| Our cl100k recount of his devtest sentences | {petrov['our_ht_tokens']} | "
      f"{petrov['our_en_tokens']} | **{petrov['our_parity']:.4f}** |")
    A("")
    A(f"*{petrov['note']}.* Our recomputed parity **{petrov['our_parity']:.4f}** lands within "
      f"±{config.PETROV_TOLERANCE} of his **{config.PETROV_TARGET}**, so the counting pipeline "
      "is validated; the FLORES+ numbers below are then our own measurement (expected close to "
      "his FLORES-200 figure, not gated to match).\n")

    # methodology
    A("## Methodology\n")
    A(f"- **Corpus.** `{config.FLORES_REPO}` split `{config.FLORES_SPLIT}`, pinned revision "
      f"`{config.FLORES_REVISION}`. Languages `hat_Latn`/`eng_Latn`/`fra_Latn`, **joined by "
      f"(split, id)** → {flores['n']} aligned sentences. FLORES+ is **eval-only by its terms**; "
      "no sentence text is committed or re-hosted in this repo (downloads land in git-ignored "
      "`ml/data/`).")
    A("- **Normalization.** NFC (è/ò consistency). No lowercasing, no accent stripping.")
    A("- **Token counting.** Content tokens only: HF tokenizers use "
      "`encode(text, add_special_tokens=False)`; tiktoken adds no special tokens; so no "
      "language gets a constant per-sentence special-token surcharge that would dilute parity.")
    A("- **Word segmentation (for tokens/word).** A word is a maximal run of Unicode letters, "
      "allowing an internal apostrophe or hyphen joining two letter-runs. **Apostrophe-clitic "
      "forms like `m'ap`, `l'ap`, `n'ap` and hyphen compounds like `pitit-pitit` count as a "
      "single word** (we do not split on internal `'`/`-`). Digits/punctuation are not words. "
      f"Word totals on this set: ht={words['ht']}, en={words['en']}, fr={words['fr']}.")
    A("- **Primary parity.** `sum(ht tokens) / sum(en tokens)` over the whole corpus (and vs "
      "French) — **not** the mean of per-sentence ratios. Uncertainty: paired bootstrap "
      f"(resample sentence indices, {config.BOOTSTRAP_REPS} reps, seed {config.BOOTSTRAP_SEED}), "
      "95% percentile CI. We also report p10/p50/p90 of the per-sentence ratio.")
    A("- **Whole-word survival.** For the core Kreyòl list "
      f"({', '.join('`'+w+'`' for w in config.CORE_WORDS)}), each checked **bare and with a "
      "leading space**; single-token = survives. Reported as fraction of "
      f"{2*len(config.CORE_WORDS)} checks.")
    A(f"- **Sentences per {config.CONTEXT_BUDGET//1024}k budget.** "
      f"{config.CONTEXT_BUDGET} ÷ mean tokens/sentence (order-independent).")
    A("- **Claude.** Separately-labeled API measurement, **not** a tokenizer count. "
      f"`client.messages.count_tokens(model=\"{config.CLAUDE_MODEL}\")`, ~"
      f"{config.CLAUDE_BATCH_SIZE} sentences/message joined by newline; the minimal-message "
      "overhead is measured and subtracted per batch; exponential backoff on 429. Because it is "
      "batched, per-sentence quantiles and survival are N/A and its CI is a coarse **batch-level** "
      "bootstrap.")
    A("  - The endpoint is an *estimate* and here reports markedly more tokens than the subword "
      "tokenizers (≈2.0 tokens/English-word vs ≈1.26 for cl100k), so Claude's **absolute** counts "
      "and tokens/word are **not** directly comparable to the tokenizer rows — only its within-API "
      "**parity** ratio (ht÷en, ht÷fr) is comparable. A 100-sentence cross-check found batched vs "
      "per-sentence parity agree to ~0.02 (1.468 vs 1.488), so the newline-batching does not "
      "distort the reported parity.\n")

    # tokenizer revisions
    A("## Tokenizers measured (pinned revisions)\n")
    A("| Label | repo / encoding | revision |")
    A("|---|---|---|")
    for r in rows:
        A(f"| {r['label']} | `{r['repo']}` | `{r['revision']}` |")
    A("")
    if any(r["label"].startswith("SmolLM3") for r in rows):
        A("> **Note:** SmolLM3's tokenizer **is** the Llama-3 tokenizer — verified 2026-07-21: "
          "identical vocab (128,256) and identical encodings on a 205-text probe (accents, "
          "clitics, numbers, code-switch). The SmolLM3 and Llama-3 rows are the same tokenizer "
          "measured twice; their digit-identical parity confirms it empirically.\n")

    # main results
    A("## Results — parity (Haitian Creole ÷ English)\n")
    A("![Kreyòl token tax parity](fertility_parity.png)\n")
    A("| Tokenizer / API | ht/en parity | 95% CI | % premium | ht/fr parity | ht tok/word | "
      "word survival | sents/8k (ht vs en) |")
    A("|---|--:|:--:|--:|--:|--:|--:|:--:|")
    for r in sorted(rows, key=lambda x: x["parity_ht_en"]):
        surv = (f"{r['survival_single']}/{r['survival_total']}"
                if r["survival_total"] != "" else "—")
        A(f"| {r['label']} | **{r['parity_ht_en']:.3f}** | "
          f"[{r['ci95_lo_ht_en']:.3f}, {r['ci95_hi_ht_en']:.3f}] | "
          f"{r['pct_premium_vs_en']:+.1f}% | {r['parity_ht_fr']:.3f} | "
          f"{r['ht_tokens_per_word']:.3f} | {surv} | "
          f"{_fmt(r['sentences_per_8k_ht'])} vs {_fmt(r['sentences_per_8k_en'])} |")
    A("")
    A("> The `claude_api_input_parity` row is an API measurement, not a tokenizer: compare its "
      "**parity** (and % premium) across rows, but not its absolute `tok/word` — the "
      "`count_tokens` estimate runs coarser than the subword tokenizers (see Methodology).\n")
    A("Per-sentence ratio spread (ht/en):\n")
    A("| Tokenizer / API | p10 | p50 | p90 |")
    A("|---|--:|--:|--:|")
    for r in sorted(rows, key=lambda x: x["parity_ht_en"]):
        A(f"| {r['label']} | {_fmt(r['p10_ht_en'])} | {_fmt(r['p50_ht_en'])} | "
          f"{_fmt(r['p90_ht_en'])} |")
    A("")

    # $ premium
    A("## Illustrative cost premium (priced APIs only)\n")
    A(f"Shown **only** for tokenizers/APIs tied to an actually-priced API. Prices are an "
      f"**operator-supplied snapshot dated {config.PRICE_DATE} and are ILLUSTRATIVE — verify "
      "against each provider's pricing page before quoting; prices drift.** The % premium above "
      "is exact and needs no price.\n")
    priced = [r for r in rows if r["api_input_usd_per_mtok"] != ""]
    if priced:
        A("| API | $/M input tokens (snapshot) | source | extra $ for the ht side of this 1012-sentence set |")
        A("|---|--:|---|--:|")
        for r in priced:
            A(f"| {r['label']} | ${r['api_input_usd_per_mtok']:.2f} | {r['price_source']} | "
              f"${r['usd_premium_flores_ht_vs_en']:.4f} |")
    else:
        A("*(No priced-API rows in this run.)*")
    A("")

    # skipped / flags / TODO
    A("## Skipped items & flags\n")
    if skipped:
        for s in skipped:
            reason = str(s["reason"]).splitlines()[0][:120].rstrip(" .(")
            A(f"- **SKIPPED {s['label']}** (`{s['repo']}`): {reason}. The script is "
              "re-runnable to fill this row later.")
    else:
        A("- None — every planned tokenizer and the Claude API measurement completed.")
    _authored_vs_translated_section(A, repo_root)
    if not any(r["label"] == config.OUR_TOKENIZER_LABEL for r in rows):
        A(f"- **Our Kreyòl BPE not included** (`{config.OUR_TOKENIZER_PATH}` absent — Workstream B "
          "not yet run). It is expected to land near/below 1.0× by construction; re-run once "
          "trained.")
    A("")

    # reproduce
    A("## Reproduce\n")
    A("```bash\ncd ml\nuv sync\n# HF_TOKEN + ANTHROPIC_API_KEY loaded from repo-root .env\n"
      "uv run python -m fertility.run\n```\n")
    A(f"Outputs: `ml/fertility/results.csv`, `ml/reports/fertility_parity.png`, this file. "
      f"Bootstrap seed `{config.BOOTSTRAP_SEED}` fixes the CIs.\n")

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    log(f"  wrote {os.path.relpath(path, repo_root)}")


def _plain(label: str) -> str:
    """Human-readable label for prose (strip the parenthetical repo)."""
    if label.startswith("claude_api_input_parity"):
        return "the Claude count_tokens API"
    return label.split(" (")[0]
